### ISSUE TITLE
Question: how do I get a mutable instance?

### ISSUE THREAD

**Issue by jcalfee** [gcanti/tcomb#110]
I need to hand off a copy to fakeIndexedDb.  When I try to store a tcomb object I get this error:
 'The data being stored could not be cloned by the internal structured cloning algorithm.'

It seems like there should be a easy way to get the mutable form.  I don't see this in the docs or in the code..  Thanks..

**Comment by gcanti** [comment]
Hi,
fakeIndexedDb uses [realistic-structured-clone](https://github.com/dumbmatter/realistic-structured-clone) and
realistic-structured-clone can't clone a tcomb instance (https://github.com/dumbmatter/realistic-structured-clone/blob/master/index.js#L53).

> It seems like there should be a easy way to get the mutable form. I don't see this in the docs or in the code

I'd use the good ol' lodash (lodash/lang/cloneDeep):

```js
describe('clone', function () {

  var structuredClone = require('realistic-structured-clone');
  var cloneDeep = require('lodash/lang/cloneDeep');
  var T = t.struct({
    name: t.Str
  }, 'T');
  var instance = T({name: 'Giulio'});

  it('should throw', function () {
    throwsWithMessage(function () {
      structuredClone(instance);
    });
  });

  it('should not throw', function () {
    var clone = structuredClone(cloneDeep(instance)); // OK!
  });

});
```
