### ISSUE TITLE
It would really be helpful if we could see which field were failing.

### ISSUE THREAD

**Issue by jcalfee** [gcanti/tcomb#116]
Our other developers and users get an exception like this.  It would really be helpful if we could see which field were failing.

```
CreateWallet failed: TypeError Invalid argument `value` = `undefined` supplied to irreducible type `Str` TypeError: Invalid argument `value` = `undefined` supplied to irreducible type `Str`
   at Object.fail (http://localhost:8080/app.js:54380:12)
   at assert (http://localhost:8080/app.js:54386:16)
   at Irreducible (http://localhost:8080/app.js:54543:8)
   at create (http://localhost:8080/app.js:54529:66)
   at new Struct (http://localhost:8080/app.js:54629:22)
   at Object.Struct [as WalletTcomb] (http://localhost:8080/app.js:54623:17)
   at _createClass.value (http://localhost:8080/app.js:55552:33)
   at WalletDb.onCreateWallet (http://localhost:8080/app.js:55524:21)
   at WalletCreate.onSubmit (http://localhost:8080/app.js:74993:42)
   at WalletCreate.<anonymous> (http://localhost:8080/app.js:58711:38)
```

**Comment by gcanti** [comment]
Hi,
those messages are just fallbacks, the real benefit is leveraging the power of Chrome DevTools:
setting "Pause on exceptions" on the "Sources" panel you can inspect the "Call Stack" in order to find out
where the error is **originated** (instead of where the error is thrown)

https://github.com/gcanti/tcomb#debugging-with-chrome-devtools

**Comment by jcalfee** [comment]
We can't recommend this out in the field for the "users."  Users will be using Firefox and Safari.  There may be other exceptions going on from time to time.  Developers may not always develop with chrome.  It is just fundamental error reporting with a broad range of benefits (nodejs as another example), I hope that you will consider it.  I noticed your structs do contain this information.  Exceptions should always contain all relevant information that is available.  Thank you...

**Comment by jcalfee** [comment]
Users are not going to want to deal with break points.

**Comment by jcalfee** [comment]
Exceptions are not always repeatable.

**Comment by gcanti** [comment]
Oh wait, sorry I didn't notice the word "users" in your first comment, just "developers". So the stack trace you reported is what a user could see in his console in production? Which version of tcomb are you using? I ask because in theory all the asserts should be stripped out in production (in v2)

**Comment by jcalfee** [comment]
Version 1.0.3 ..

**Comment by jcalfee** [comment]
We are working on a pre-alpha release now.  Anytime we roll out new code it will involve a migration of IndexedDb data.  So, I foresee an ongoing use for the information during that testing roll out period.  Additionally, we don't have any control over how old a indexed db can get.  So, I would probably consider keeping the asserts in all cases.

**Comment by gcanti** [comment]
I see. Ok, I'll think about it and I'll try do add some context to error messages.

**Comment by gcanti** [comment]
Hi @jcalfee,

The message might have the following general form:

```
Invalid value <value> supplied to <context>
```

where `context` is a slash-separated array with the following properties:

- the first element is the name of the "root"
- the following elements have the form: `<field name>: <field type>`

**Example**

```js
var Person = t.struct({
  name: t.String
}, 'Person');

var User = t.struct({
  email: t.String,
  profile: Person
}, 'User');

var myuser = User(1);
// => Invalid value 1 supplied to struct User (expected an object)

var myuser = User({ email: 1 });
// => Invalid value 1 supplied to User/email: Str

myuser = User({ email: 'email', profile: { name: 2 } });
// => Invalid value 2 supplied to User/profile: Person/name: Str
```

The message would be compact but full of context / types.
What do you think?

**Comment by jcalfee** [comment]
Very professional... Looks like you covered the entire tree.  If you need to report just the leaf for some reason that should do the trick.  I definitely like your solution it will cover everything and be one less thing that may come up in future..

**Comment by gcanti** [comment]
Hi @jcalfee,

I just released v1.1.0 containing the new feature (it has been more difficult than I thought).

https://github.com/gcanti/tcomb/releases/tag/v1.1.0

Let me know how it goes.

**Comment by jcalfee** [comment]
This is tcomb v1.1.0. 

The amount: Number is new so this is probably an error with a string amount going into the number type:

```
alanceClaim TypeError: Invalid value "4510050000" supplied to {chain_balance_record: Object, private_key_id: Number, is_claimed: ?Boolean, vested_balance: ?{amount: Number, asset_id: String}}/vested_balance: ?{amount: Number, asset_id: String}/amount: Number
    at Object.fail (http://localhost:8080/app.js:74129:12)
    at assert (http://localhost:8080/app.js:74135:16)
    at Irreducible (http://localhost:8080/app.js:74301:8)
    at create (http://localhost:8080/app.js:74287:72)
    at new Struct (http://localhost:8080/app.js:74397:22)
    at create (http://localhost:8080/app.js:74287:43)
    at Maybe (http://localhost:8080/app.js:74500:38)
    at create (http://localhost:8080/app.js:74287:72)
    at new Struct (http://localhost:8080/app.js:74397:22)
    at Function.Struct.update (http://localhost:8080/app.js:74419:15)
```
So after adjusting the amount to a string I got another error:
```
BalanceClaim TypeError: Invalid value 1000 supplied to {chain_balance_record: Object, private_key_id: Number, is_claimed: ?Boolean, vested_balance: ?{amount: String, asset_id: String}}/vested_balance: ?{amount: String, asset_id: String}/amount: String
```
A simple message might look like: 
`TypeError: Invalid value 1000 supplied to vested_balance.amount: String`

Are these errors on `vested_balance.amount`?  How do I read them?

**Comment by gcanti** [comment]
> Are these errors on vested_balance.amount?

Yes. It seems that sometimes you pass a string and sometimes you pass a number.

Suggestion: if you want more readable message, give a name to your types:

```js
var VestedBalance = t.struct({
  amount: t.String,
  asset_id: t.String
}, 'VestedBalance'); // <= you'll see this name in the error message instead of "{amount: String, asset_id: String}"
```

**Comment by jcalfee** [comment]
Yes we need to fix that in our API .. thanks for the tip I'll do that.

**Comment by jcalfee** [comment]
> Yes. It seems that sometimes you pass a string and sometimes you pass a number.

Another good reason to use tcomb
