### ISSUE TITLE
irreducible throws quietly on recursive datastructures

### ISSUE THREAD

**Issue by tmcw** [gcanti/tcomb#123]
<img width="713" alt="2015-08-24 at 10 47 am" src="https://cloud.githubusercontent.com/assets/32314/9443147/839eea74-4a4d-11e5-8dbe-964a15426c06.png">

This throws every time: it's not a user-facing error, but having a lot of caught exceptions can make debugging other exceptions trickier. Seems like the way around this would be to only evaluate the assertion message if the assertion actually fails.

**Comment by gcanti** [comment]
Hi @tmcw, thanks for the report.
Not sure I'm follow, is the `stringify` function which throws every time?
In order to reproduce the issue could you please show me an example of a recursive data structure for which it throws every time?

**Comment by gcanti** [comment]
> Seems like the way around this would be to only evaluate the assertion message if the assertion actually fails

Anyway, this seems an excellent idea, also performance-wise. I added an issue:

https://github.com/gcanti/tcomb/issues/124

**Comment by tmcw** [comment]
@gcanti yes, the stringify function is a wrapper around [JSON.stringify](https://github.com/gcanti/tcomb/blob/a26a623d7565eae3adb29b6b892c38b5037538e6/index.js#L4-L10), which will throw the recursive-datastructure error. Since the message is evaluated whether it's needed or not (whether or not the assertion actually fails), this means 1 thrown exception per type check.

**Comment by gcanti** [comment]
Hi @@tmcw,
Just shipped v2.3 if you want to give it a spin

**Comment by tmcw** [comment]
:+1: awesome, thanks - upgraded, and it dramatically cuts down on caught exceptions in my app
