### ISSUE TITLE
Handling the "update" method for union

### ISSUE THREAD

**Issue by jgoux** [gcanti/tcomb#127]
Hello,
if we call the "update" method on a union type, it throws a `undefined is not a function` error.
For this particular case, a default implementation of update could be implemented for union types, so it delegates to one of its underlying type based on the dispatch method.
Based on the example I provided here https://github.com/gcanti/tcomb/issues/126 : 
```js
const TodoListAggregate.Command = union([AddTodo, EditTodo])
TodoListAggregate.Command.dispatch(customDispatch)
const Command = union([TodoListAggregate.Command, AnotherAggregate.Command])
const command = Command(fooBar)
const enrichedCommand = Command.update(command, {
    data: {meta: {"$merge": {date: new Date()}}}
}) // use the internal dispatch to find the corresponding type, then call its update method
```

**Comment by gcanti** [comment]
I really don't know why I didn't implement an `update` function for unions...

And it seems also easy:

```js
Union.update = function (instance, spec) {
  return Union(exports.update(instance, spec));
};
```

You are the master of unions :)
Thanks for your insights. Again, do you like to submit a PR?
