### ISSUE TITLE
Allow a single type in the union combinator

### ISSUE THREAD

**Issue by jgoux** [gcanti/tcomb#130]
Hello again !
I know it's not mathematically true , but could we allow a single type for the union combinator ?
Right now it throws an error, but without it all works at expected.
This demand is for convenience purpose only, because as the code evolving, it's easier to just add types in an array than rewrite types as unions.

**Comment by gcanti** [comment]
> This demand is for convenience purpose only

Did you try starting with an alias?

```js
const MyFirstUnionType = t.struct(...);

// instead of t.union...
const MyUnion = MyFirstUnionType;
// then when there is a 2nd type...
const MyUnion = t.union([MyFirstUnionType, MySecondUnionType]);
```

**Comment by jgoux** [comment]
Seems fair ! :p
