### ISSUE TITLE
Generic Datatypes

### ISSUE THREAD

**Issue by mlegenhausen** [gcanti/tcomb#131]
I would like to have a opinion about generic datatypes.

```js
var A = struct({});
var B = struct({ aList: list(A) });
```

Now I would like to have a `BExtended` that overwrites `list(A)`. My approach would be:

```js
var B = function (T) {
  return struct({
    aList: list(T)
  });
};
```

so I can construct a subclass that can exchange the list type.

```js
var AExtended = A.extend({});
var BExtended = B(AExtended).extend({
});
```

@gcanti how do you handle such situations?

**Comment by gcanti** [comment]
> My approach would be:

```js
var B = function (T) {
  return struct({
    aList: list(T)
  });
};
```

Hi,
Indeed that is what I do, that is, defining a custom combinator (the `B` function in your case)

```js
function mycombinator(T, name) {
  return struct({
    aList: list(T)
  }, name); // <= give the type a name for better debug messages
}
```
