### ISSUE TITLE
Enums combinator (question)

### ISSUE THREAD

**Issue by ivan-kleshnin** [gcanti/tcomb#134]
I noticed that you define `enums` through object literals with `true` values and then add a wrapper `.of` which translates array of allowed strings to this object literal.

I'm interested why array was not chosen at the beginning.

The function 

```js
function enums(obj) {
  return subtype(Str, function (s) {
    return obj.hasOwnProperty(s);
  });
}
```

could obviously be 

```js
function enums(array) {
  return subtype(Str, function (s) {
    return array.indexOf(s) >= 0;
  });
}
```

I'm sure it wasn't an accidental choice and I'd like to know a motivation.

**Comment by gcanti** [comment]
For 2 reasons:

1. performance, using a hash lookup should perform better
2. you might want to store some related info, you could use the object values as stores:

```js
const Country = t.enums({
  IT: {
    description: 'Italy',
    language: 'Italian',
    locale: 'it-IT'
  },
  US: {
    description: 'United Stated',
    language: 'English',
    locale: 'en-US'
  }
}, 'Country');
```

and then retrive them with:

```js
Country.meta.map['IT']; // => { description: 'Italy', language: 'Italian', locale: 'it-IT' }
```

**Comment by ivan-kleshnin** [comment]
Aha, that's exactly related to my previous typo report. Now it's pretty clear.
Thank you, Giulio.
