### ISSUE TITLE
more functional t.match

### ISSUE THREAD

**Issue by giogonzo** [gcanti/tcomb#139]
I know I'm late to the `t.match` party (and it's probably too late to do this without breaking changes), but I found myself doing something like the following pretty frequently:

```js
const getVal = partialRight(t.match,
  t.Str, v => 'something',
  t.Num, v => 'something else',
  // ...
);
/* ... */
const val = getVal(v)
```

wouldn't be just better to have the `value` as *last* parameter of `t.match`?
(even better: support both, but not sure how...)

Speaking of `t.match`, aren't optional `guard`s kind of redundant considering we have `t.subtype`?

BTW: thanks for continuous support and adding new features :beers:

**Comment by gcanti** [comment]
Hi @giogonzo !

> wouldn't be just better to have the value as last parameter of t.match?

The value in first position just reads better IMHO

```js
const s = t.match(value,
  t.String, () => 'a string',
  t.Number, () => 'a number'
);

// against
const s = t.match(
  t.String, () => 'a string',
  t.Number, () => 'a number',
  value
);
```

> (even better: support both, but not sure how...)

Maybe I could add a `partial` prop to `match`:

```js
t.match.partial = (...cases) => (v) => t.match(v, ...cases);
```

So you can write

```js
const matcher = t.match.partial(
  t.String, () => 'a string',
  t.Number, () => 'a number'
);

matcher(1); // => 'a number'
```

> Speaking of t.match, aren't optional guards kind of redundant considering we have t.subtype?

Probably yes, but it's more general: without them I should write in the docs: "You must define subtypes in order to implement guards", while now is just an option

/cc @jgoux

**Comment by giogonzo** [comment]
>The value in first position just reads better IMHO

Sure, when used like that.. 

>Maybe I could add a partial prop to match:

That would be perfect for my use case 

>Probably yes, but it's more general: without them I should write in the docs: "You must define subtypes in order to implement guards", while now is just an option

Understandable. It's just me feeling better when there's only one way of doing something 

Anyway, all of the above is super minor and adds nothing really new so feel free to close this. Thanks for getting back!
