### ISSUE TITLE
Is version 1.x for the browser and version 2.x for node?

### ISSUE THREAD

**Issue by rmilesson** [gcanti/tcomb#150]

**Comment by gcanti** [comment]
tcomb can be used in the browser if you use something like browserify / webpack, since it uses `process.env.NODE_ENV` tests in order to strip the asserts in production

**Comment by rmilesson** [comment]
Ah, that explains a lot. Might I clarify that in the README?

**Comment by gcanti** [comment]
Sure, thanks
