### ISSUE TITLE
Union of structs

### ISSUE THREAD

**Issue by dshimkoski** [gcanti/tcomb#151]
Thanks for the sweet library!

I've implemented a union of structs as follows, but I'm curious to know why it hasn't been implemented by default. Is there a dragon lurking in the shadows here?

```
  Struct.is = function (x) {

    if (x instanceof Struct) {
      return true;
    }

    var keys = Object.keys(props);
    var keyLen = keys.length;
    var xLen = Object.keys(x).length;

    var resolved = 0;

    for (var i = 0; i < keyLen; i++) {

      var key = keys[i];
      var prop = props[key];
      var val = x[key];

      if ((isNil(val) && isMaybe(prop)) || is(val, prop)) {
        ++resolved;
      }

    }

    if (resolved === keyLen) {
      return true;
    }

  };
```

Just to give you a little context, I'm trying to support a model that looks something like this...

```
export const Url = struct({
  href: Str,
  type: enums.of('x y z')
}, 'Url');

export const Expander = struct({
  isOpen: maybe(Bool),
  items: Any
}, 'Expander');

export const Item = struct({
  id: Str,
  title: maybe(Str),
  body: union([Url, Expander])
}, 'Item');

Expander.meta.props.items = list(Item);
```

This lets me do the following (which is awesome of course)...
```
Item({
  id: 'root',
  body: {
    items: [{
      id: 'child',
      body: {
        href: 'beep',
        type: 'x'
      }
    }]
  }
});
```

But not all that helpful when validation fails...
```
TypeError: [tcomb] Invalid value {
  "items": [
    {
      "id": "child",
      "body": {
        "href": "beep",
        "type": "wrong value buried in deep tree"
      }
    }
  ]
} supplied to Item/body: Url | Expander (no constructor found)
```

So first question, dragons? Second, any idea how I might improve the error reporting situation?

**Comment by dshimkoski** [comment]
Hmm. I just realized that overwriting the `is` method kills the type information, since the constructor basically validates the structure but then returns the value itself...

```
    if (Struct.is(value)) { // implements idempotency
      return value;
    }
```

I can work around this by bringing the instanceof check up into the constructor instead...
```
    if (value instanceof Struct) { // implements idempotency
      return value;
    }
```

Anything wrong with this approach?

**Comment by dshimkoski** [comment]
Seems like my `is` function and the check at the top of the constructor kills type info...

```
    if (Struct.is(value)) { // implements idempotency
      return value;
    }
```

This will essentially validate the data and hand it back to the caller without wrapping it first.

Is it enough to change this to an `instanceof` check or will that produce undesirable effects?

**Comment by gcanti** [comment]
Hi,
basically `supplied to Item/body: Url | Expander (no constructor found)` means:

- the field `body` of the type `Item`...
- ...is a union of types `Url` and `Expander`...
- ...but for the value `"items": [..]` I can't decide if it's a `Url` or a `Expander` (no constructor found)

You can fix that defining the `dispatch` static function on the union (https://github.com/gcanti/tcomb/blob/master/GUIDE.md#the-dispatch-function):

```js
const Url = t.struct({
  href: t.Str,
  type: t.enums.of('x y z')
}, 'Url');

const Expander = t.struct({
  isOpen: t.maybe(t.Bool),
  items: t.Any
}, 'Expander');

const Body = t.union([Url, Expander]);

Body.dispatch = function (x) {
  return x.href ? Url : Expander;
};

const Item = t.struct({
  id: t.Str,
  title: t.maybe(t.Str),
  body: Body
}, 'Item');

Expander.meta.props.items = t.list(Item);

console.log(Item({
  id: 'root',
  body: {
    items: [{
      id: 'child',
      body: {
        href: 'beep',
        type: 'x'
      }
    }]
  }
}));
```

**Comment by dshimkoski** [comment]
I have used Union.dispatch a few times elsewhere, so I'm not sure why this didn't occur to me. Thank you nonetheless!
