### ISSUE TITLE
Do not update a model instance when no changes occur

### ISSUE THREAD

**Issue by a-s-o** [gcanti/tcomb#153]
Hello,

I would like to know whether it is possible to implement `T.update` in a way so that the it does not return a new instance if no changes occur as a result of applying update specs.

Example ([view on requirebin](http://requirebin.com/?gist=ae046d8074c6d48fd8d2)):
```javascript
const t = require('tcomb');

const Person = t.struct({ name: t.Str, money: t.Num }, 'Person');

Person.prototype.pay = function (amount) {
  return Person.update(this, {
    money: { $set: this.money + t.Num(amount) }
  });
};

try {
  const me = new Person({ name: 'me', money: 0 });
  
  // This is what currently happens in tcomb (both tests pass)
  t.assert(me.pay(1).money === 1, 'ensure property is updated');
  t.assert(me !== me.pay(1), 'return different instance if properties changed');

  // THIS IS THE REQUESTED FEATURE (currently fails)
  t.assert(me === me.pay(0), 'return same instance if properties did not change');

} catch (ex) {
  document.getElementById('output').innerHTML = ex;
}
```

This would be very useful for easier checking of state changes, for example in React's `shouldComponentUpdate`. In my case, I am using `cerebral-tcomb` to manage the app state tree and sometimes incoming state updates do not change anything but still trigger a redraw.

**Comment by gcanti** [comment]
Hi @a-s-o !
Thanks for the detailed description. It's definitely possible. I've just merged on master a possible fix:

https://github.com/gcanti/tcomb/commit/b8281f6177bfe08946a36848b7a889febc54836d

**Comment by a-s-o** [comment]
Wow, thanks for updating that fast. Very much appreciated. I will test it out.

**Comment by gcanti** [comment]
Great, thanks. Btw I've just released the first version of https://github.com/gcanti/babel-plugin-tcomb. It's a Babel plugin for runtime type checking using tcomb. You can annotate a function (arguments and return type) with tcomb types. Let me know what you think. Cheers
