### ISSUE TITLE
deprecated types

### ISSUE THREAD

**Issue by benmonro** [gcanti/tcomb#155]
Hello,

I noticed that you mention here that t.Str (and other aliases) are deprecatred: https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md

I'm not quite clear by the wording... is t.String deprecated or t.Str?  If so the use of these alisases should be updated in all of the guides for tcomb, -form & -validation...

**Comment by gcanti** [comment]
Hi, 
thanks for pointing out. 

tcomb and tcomb-validation example should be ok. I must update tcomb-form though: https://github.com/gcanti/tcomb-form/issues/228
