### ISSUE TITLE
Configure freeze and type assertions separately?

### ISSUE THREAD

**Issue by jbalboni** [gcanti/tcomb#156]
Hi,

Do you have any interest in making the Object.freeze call and the type assertions configurable separately? With the app I'm working on, we have environments where I'd like to throw exceptions for type errors, but I don't want the overhead of Object.freeze.

I can work on a PR if that's something you'd want to do.

**Comment by gcanti** [comment]
Hi,

It's interesting, what's your use case? (*)

Warning: You possibly loose a big portion of safety since assertions are written assuming immutability.

Having said this, I count 4 occurrences of `Object.freeze` in this form:

```js
if (process.env.NODE_ENV !== 'production') {
  Object.freeze(this);
}
```

How do you think to implement that behaviour? From the top of my head I can think of

1) adding an additional condition for envify / DefinePlugin

```js
if (process.env.NODE_ENV !== 'production' || process.env.NODE_ENV !== '???') {
  Object.freeze(this);
}
```

2) adding a runtime check

```js
if (exports.doFreeze) {
  Object.freeze(this);
}
```

3) other...?

(*) you don't have to, I'm just curious

**Comment by jbalboni** [comment]
I was thinking 2), a runtime check that you could override (similar to the fail function).

I was thinking of 2 cases:

1. Where I work, our staging environment is supposed to be as close as possible to production, but we do a lot of manual QA testing there and it would be nice to see errors for type issues. But I was under the impression that Object.freeze would be a decent performance hit. I might be wrong about that. Doing some more research, it looks like I probably am (outside of Safari). In any case, I thought skipping the freeze and keeping the type assertions would be a reasonable compromise.

2. Another benefit of a configurable runtime check for me is that our Browserify bundles are the same between our staging environment and production, so I don't think I can use process.env.NODE_ENV to differentiate them, but I do have other variables I can check at runtime.

**Comment by gcanti** [comment]
I'd like to preserve the dead code elimination in production. What about a specific env variable? Something like

```js
if (process.env.NODE_ENV !== 'production' && process.env.TCOMB_DO_FREEZE !== false) {
  Object.freeze(this);
}
```

Result:

- development => frozen
- production => not frozen
- development but TCOMB_DO_FREEZE=false => not frozen

**Comment by jbalboni** [comment]
Sorry, got sidetracked from this.

The more I think about it, the more I think that the runtime check is really what I want. But I understand wanting to keep the dead code elimination. I'm still figuring out exactly how I'd use tcomb, so I'm going to go ahead and close this.
