### ISSUE TITLE
add TypeScript definition file

### ISSUE THREAD

**Issue by gcanti** [gcanti/tcomb#160]

**Comment by jcristovao** [comment]
Is the one from [DefinetelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/tcomb), refering to version 1.0.3 a good starting point, or too much has changed?

**Comment by gcanti** [comment]
Hi,

Yes it's good starting point, however there are several changes in v2. 
This is my first (and incomplete) attempt https://github.com/gcanti/tcomb/blob/typescript/tcomb.d.ts.
I'm using Microsoft Visual Studio Code in order to check the results in terms of IDE hints.

The main problem I'm facing is how to convince tsc that the combinators return a type:

```js
const Url = t.irreducible<string>('Url', () => true);

function f(url: Url) {} // error: Cannot find name 'Url'
```

I found a workaround giving a fake `t` member to `Type<T>` and then using a type query:

```js
const Url = t.irreducible<string>('Url', () => true);

function f(url: typeof Url.t) {} // ok
```

not sure if is the most elegant and handy solution though

/cc @hansrwindhoff @DanielRosenwasser @jedmao

**Comment by DanielRosenwasser** [comment]
I think that's not too bad; if users find it cumbersome, they can always write

```ts
const Url = t.irreducible<string>('Url', () => true);
type Url = typeof Url.t;

function f(url: Url) {} // ok
```

Or even

```ts
type Url = string;
const Url = t.irreducible<Url>('Url', () => true);

function f(url: Url) {} // ok
```

**Comment by gcanti** [comment]
@DanielRosenwasser Thanks for the heads up! Then I proceed with the other combinators...

**Comment by gcanti** [comment]
Hi all. 
Just pushed a first version to `typescript` branch https://github.com/gcanti/tcomb/tree/typescript 

Files:

- tcomb.d.ts
- tcomb-tests.ts

I'd love to hear your feedback.

Cheers,
Giulio

**Comment by jedmao** [comment]
Personally, I would prefer the whole library be converted into TypeScript so the definition files could be generated and always in sync, but that's just me.

**Comment by DanielRosenwasser** [comment]
Hey Giulio

I haven't completely looked at the typings yet, but in order for TypeScript to appropriately resolve the `.d.ts` file, you should either add a `"typings"` field to your `package.json` or rename `tcomb.d.ts` to `index.d.ts`

See [our wiki page on the matter](https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages) for more details.

**Comment by DanielRosenwasser** [comment]
One strange thing I've noticed is you have signatures like the following:

```ts
export function union<T>(types: Array<Type<any>>, name?: string): Union<T>;
```

Should `any` be `T`? Is it possible that you meant to write this?

```ts
export function union<T>(types: Array<Type<T>>, name?: string): Union<T>;
```

________

Additionally, I think `Predicate` should potentially be generic and defined as a type guard:

```ts
type Predicate<T> = (x: any) => x is T;
```

Let me know your thoughts on both of these.

**Comment by gcanti** [comment]
Great advices, thanks a lot @DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
:tada:

**Comment by jcristovao** [comment]
Thanks :+1:
