### ISSUE TITLE
Implementation of a general deserialize function

### ISSUE THREAD

**Issue by gcanti** [gcanti/tcomb#169]
**Problem**: write a function which, given a JSON / JavaScript blob and a `tcomb` type, returns an instance of that type, performing conversions automatically if required (ex: from a date in ISO-8601 to a `Date` object)

**Proposed solution**. A function `deserialize` with the following signature:

```js
(value: any, type: TcombType) => type
```

and a series of `type.fromJSON(value: any) => type` helpers

**Reference** [Runtime type introspection, playing with structs](https://github.com/gcanti/tcomb/blob/master/docs/GUIDE.md#runtime-type-introspection-playing-with-structs) in the GUIDE.md file

**Comment by gcanti** [comment]
Let's kick off the discussion starting with this comment by @grahamlyus https://github.com/gcanti/tcomb/issues/165#issuecomment-173015631:

Anyway, in my scenario I found a few issues with the deserialise function:
* I needed to override `fromJSON` on a `refinement` (`subtype`).
* `list` was missing.
* unknown props would throw an error, rather than be ignored as with normal construction.

Here's my version (uses Babel):

```js
t.Date.fromJSON = (s) => s ? new Date(s) : null // allow conversion from ISO-8601

// Deserialize to tcomb type, allows for conversions via a fromJSON function on the type.
export const deserialize = (value, type) => {
  // Ignore unknown types, probably extra data that will be ignored anyway.
  if (!type) {
    return value
  }

  const { kind } = type.meta
  switch (kind) {
    case 'struct':
      return type(Object.keys(value).reduce((acc, key) => {
        acc[key] = deserialize(value[key], type.meta.props[key])
        return acc
      }, {}))
    case 'list':
      return type(value.map((element) => deserialize(element, type.meta.type)))
    case 'maybe':
      return deserialize(value, type.meta.type)
    case 'subtype': // the kind of refinement is 'subtype' (for legacy reasons)
      // See if custom serializer, else delegate to supertype.
      if (t.Function.is(type.fromJSON)) {
        return type.fromJSON(value)
      }
      return deserialize(value, type.meta.type)
    case 'enums':
    case 'irreducible':
      if (t.Function.is(type.fromJSON)) {
        return type.fromJSON(value)
      }
      return value
  }
}
```

Maybe the `maybe` case should handle `null`, rather than my `t.Date.fromJSON` example?

Are there any other types that should be handled? Should the default case throw an error or return value?

**Comment by gcanti** [comment]
Just pushed an implementation for review here https://github.com/gcanti/tcomb/blob/169/lib/fromJSON.js

/cc @grahamlyus

**Comment by grahamlyus** [comment]
Great, thanks! Works for me.
