### ISSUE TITLE
Refinement is not a type?

### ISSUE THREAD

**Issue by Firfi** [gcanti/tcomb#177]
Hey @gcanti ,

I have code like this:

```

const password = t.struct({
  password: t.maybe(t.Str) // it is refinement for t.maybe(t.Str) in real world but it isn't important here
});

const passwordRequired = t.refinement(password, (v) => !!v.password, 'PasswordRequired');

const signInForm = t.struct({
  email: t.Str // it it refinement too in app
}).extend([passwordRequired], 'signInForm');


```

it gives me an error `[tcomb] Invalid argument mixins supplied to extend(mixins, name), expected an array of objects or types`. If I change code to

```
const signInForm = t.struct({
  email: t.Str // it it refinement too in app
}).extend([password], 'signInForm');
```

where [password] isn't a `refinement` anymore but pure `struct`, it works fine.

Is it supposed to work like this? Can I extend refinements?

Thanks

**Comment by gcanti** [comment]
Hi @Firfi

Extending refinements is not supported at the moment, the error message is misleading, should be `expected an array of objects or structs`, I'll fix that.

**Comment by Firfi** [comment]
Supporting refinements makes sense for me. Maybe I am doing it wrong?

I.e. I have two forms in two different parts of application that 'mixin' some behavior like addressBehavior. addressBehavior is a struct with zip (zip code), address, country and state. country is a enum of every country codes. If country code is not US, I want to leave zip and state as t.maybe(t.Str), however, if country is US, I want to do additional check for zip and state presence. 

As I see currently, this check should be implemented as a refinement over struct, but I cannot extend it or extend with it to mixin in my two forms then.

Maybe I understand refinement objective wrong? Also, maybe there is some workarounds?

**Comment by gcanti** [comment]
> Supporting refinements makes sense for me

I agree, it's just not supported at the moment. We need to draft a spec though, I'll open an issue for this.

> Also, maybe there is some workarounds?

Maybe. If acceptable, the simplest one would be to assign the `addressBehavior` refinement to a `address` field instead of mix it in the main type.

**Comment by gcanti** [comment]
@Firfi FYI tcomb v3.1.0 now supports extending refinements
