### ISSUE TITLE
"Si vis pacem, para bellum" relevance

### ISSUE THREAD

**Issue by Jameskmonger** [gcanti/tcomb#184]
What is the relevance of the quote

> "Si vis pacem, para bellum" - (Vegetius 5th century)

From the [README.md document](https://raw.githubusercontent.com/gcanti/tcomb/9059ceb1d7fa36c4742915de7bfb5dabcd5dc50a/README.md) ?

As I understand it, it means "If you want peace, prefer for war", but I don't understand the relevance between the quote and the library...

**Comment by gcanti** [comment]
Disclaimer: I'm not a native speaker so probably what follows is an ugly translation.

That latin *sententia* can be interpreted as "one of the most effective means to ensure peace is to be armed and able to **defend** itself".

Nerdy meaning: we are naked and helpless in front of the dynamic nature of the enemy (JavaScript). We need sentries (runtime type-checking) all over the places to protect us from aggressions (type errors). Once (tcomb's) armies are in place, there's no way invaders can cross the (IO) walls of our reign (code).

**Comment by Jameskmonger** [comment]
Wow thanks for explaining - that is one clever use of the phrase! :fireworks: :8ball:
