### ISSUE TITLE
Standard list's functions like .map()

### ISSUE THREAD

**Issue by bsideup** [gcanti/tcomb#185]
Hi!

What is the recommended way to work with collections in tcomb? 

i.e. if I want to migrate to tcomb from my old code, and I have a lot of `myArray.map(it => ...)` ?

**Comment by gcanti** [comment]
Instances are not boxed, this means that `tcomb` works great with standard array's functions like `map`, `filter`, and libraries like  `lodash`, `Ramda`, etc.
The only exception are `struct`s.

**Comment by bsideup** [comment]
@gcanti somehow it didn't work for me :( Could you please provide an example (with standard .map() function)? Thanks!

**Comment by gcanti** [comment]
> somehow it didn't work for me

Not sure what you mean, maybe it's better if you could provide a simple snippet of your codebase that you want to migrate which is causing problems to you.

Anyway, say you have a list of words and you want to get the corresponding list of lengths:

```js
// without tcomb
const words = [
  'a',
  'list',
  'of',
  'words'
]

const lengths = words.map(w => w.length)

console.log(lengths) // => [1, 4, 2, 5]
```

Now you can add type safety like this:

```js
// with tcomb
import t from 'tcomb'

// define the type representing a list of strings
const ListOfStrings = t.list(t.String)

const words = ListOfStrings([
  'a',
  'list',
  'of',
  'words'
])

// here words is still a native array and it has been type-checked, words is also immutable (in development):
// words[0] = 'hello' // => throws "TypeError: Cannot assign to read only property '0' of object '[object Array]'" (in strict mode)

const lengths = words.map(w => w.length)

console.log(lengths) // => [1, 4, 2, 5]
```

**Comment by bsideup** [comment]
@gcanti ah, ok, thanks! I was thinking that tcomb will behave similarly to ImmutableJS, where resulting object will pass equality checks after merge. Thanks!
