### ISSUE TITLE
Accessing an enum property

### ISSUE THREAD

**Issue by alvaromb** [gcanti/tcomb#190]
### Version

3.0.0

### Expected behaviour

Access an `enum` property.

### Actual behaviour

I have to do the following: `MyEnum.meta.map.PROPERTY`

### Steps to reproduce

1. Create an `enum`.
2. Access any of it's properties.

```
```

This is a complete noob question, but shouldn't `enum` provide a way to query its values instead of accessing `meta.map`? Just like a plain freezed object.

**Comment by gcanti** [comment]
For consistency, all runtime type introspection infos are stored in a `meta` object:

**refinement**

```js
const MyRefinement = t.refinement(t.String, mypredicate)

// meta object
{
  kind: 'subtype',
  type: t.String,
  predicate: mypredicate
}
```

**list**

```js
const MyList = t.list(t.String)

// meta object
{
  kind: 'list',
  type: t.String
}
```

**enums**

```js
const MyEnum = t.enums(map)

// meta object
{
  kind: 'enums',
  map: map
}
```

etc...

Is there a particular reason you want to access the enum values by writing `MyEnum.PROPERTY` instead of `MyEnum.meta.map.PROPERTY` (besides being shorter)?

**Comment by alvaromb** [comment]
Nope, I just thought that it would be nice to access it in a more shorter way :stuck_out_tongue_winking_eye:

**Comment by alvaromb** [comment]
I'm not reopening this, but another reason is that `flow` can autocomplete the object properties when simply freezing an `Object`.
