### ISSUE TITLE
How to use tcomb in webpage

### ISSUE THREAD

**Issue by geohuz** [gcanti/tcomb#191]
I'm wondering if I can include the tcomb lib in my webpage like 
```
<script src="tcomb.js">
```

I can only see the usage from npm, but how can I include it in a regular way? Sorry for my naive question.

**Comment by gcanti** [comment]
Something like webpack or browserify would work. This is an example using webpack:

https://github.com/gcanti/tcomb/blob/benchmark/webpack.config.js

Will output 2 files:

- `dist/tcomb.js` (development)
- `dist/tcomb.min.js` (production) `Object.freeze` calls and asserts stripped out

**Comment by geohuz** [comment]
Thanks!
