### ISSUE TITLE
Add `Struct.omit`

### ISSUE THREAD

**Issue by nickclaw** [gcanti/tcomb#194]
Have you considered adding the ability to create a struct that is a subset of another struct?

For example, in the same style as the `Extending a struct` docs.

## Creating a subset of a struct

Every struct constructor owns an

```js
omit(keys: string | Array<string>, name?: string) => TcombStruct
```

function where `keys` can be a string or array of strings, representing the keys that should be omited from the original struct.

**Example**

```js
const Point2D = Point3D.extend('z', 'Point2D');
const Point1D = Point3D.extend(['z', 'y'], 'Point1D');
```

**Comment by gcanti** [comment]
Hi @nickclaw,

I'm afraid it wouldn't play well with prototypal inheritance:

```js
const Rectangle = t.struct({
  width: t.Number,
  height: t.Number
});

Rectangle.prototype.getArea = function () {
  return this.width * this.height;
};

const Cube = Rectangle.extend({
  thickness: t.Number
});

// typeof Cube.prototype.getArea === 'function'
Cube.prototype.getVolume = function () {
  return this.getArea() * this.thickness;
};
```

If I define `Rectangle` in terms of `Cube`, what should I do with the `getVolume` method? 
I think it's more natural and clearer always to **extend** structs.

**Comment by nickclaw** [comment]
You're right, I started to work on a pull request when I ran into the problem with prototypes.

I'll close this, but you do you have any suggestions on a way to only validate a part of a struct. The use case I'm trying to solve is where I have a previously validated model in the database, and I'd like to the update several properties without loading the entire model again.
