### ISSUE TITLE
Would you consider an interface type?

### ISSUE THREAD

**Issue by ctrlplusb** [gcanti/tcomb#195]
e.g.
```
const Foo = t.inter({
  x: t.Number,
  y: t.Number
}, 'Foo');

const foo = Foo({ x: 1, y: 2 }); // throws - not a function.
Foo.is({ x: 1, y: 2 }); // true
Foo.is({ x: 1, y: 2, z: 3 }); // true
Foo.is({ x: 1, y: '2' }); // false
Foo.is({ x: 1 }); // false
t.assert(Foo.is({ x: 1 })); // throws - interface requirements not met...
```

Could be helpful in keeping things DRY.

**Comment by ctrlplusb** [comment]
Saw a link off to the tcomb validators. Interesting. Essentially they provide the above. A bit verbose, but maybe a candidate for the Babel plugin?

**Comment by ctrlplusb** [comment]
Actually just seen that it's strict on its validation, i.e. no additional props.

**Comment by gcanti** [comment]
If I understand correctly, you are proposing a new combinator similar to `t.struct` except for its `is` static function which would use structural typing instead of `instanceof` in its implementation, right?

**Comment by ctrlplusb** [comment]
Exactly yes, I would like to enforce an interface, not a class.

**Comment by gcanti** [comment]
My analysis so far:

**Requirements by examples**

```js
const Foo = t.pojo({
  x: t.Number,
  y: t.Number
}, 'Foo');

// tcomb types are glorified identity functions
const foo = Foo({ x: 1, y: 2 }); // => { x: 1, y: 2 } (not even touched)
Foo.is({ x: 1, y: 2 }); // => true
// should allow additional props
Foo.is({ x: 1, y: 2, z: 3 }); // => true
// should check types
Foo.is({ x: 1, y: '2' }); // => false
// shouldn't allow missing props
Foo.is({ x: 1 }); // => false

const Point = t.struct({
  x: t.Number,
  y: t.Number
});

const Bar = t.pojo({
  point: Point
});

// should "deserialize" prop values
const bar = Bar({point: {x: 0, y: 0}});
Point.is(bar.point); // => true
```

**Missing requirements**

Which name? `pojo`, `interface`?
Should the combinator use `hasOwnProperty('prop')` or `['prop']`? Using the latter would allow to define interfaces including prototype methods:

```js
const Serializable = t.pojo({
  serialize: t.Function
})

Point.prototype.serialize = () => ....

function doSerialize(serializable: Serializable) {
  ...
}

doSerialize(point); // => ok
```


**Performance**

The `is` static function, using structural typing instead of `instanceof` in its implementation, will be slower.

**Additional features**

Pojo types could have an `extend()` static function similar to Struct's `extend`.

**Consequences on other combinators**

- struct's `extend` could accept also pojo types other than objects and structs
- struct's `getDefaultName` should be changed in order to distinguish them from pojos

**Consequences on other libraries**

- `tcomb-validation`: add new validator
- `tcomb-doc` add new combinator
- `bable-plugin-tcomb`: handy for https://github.com/gcanti/babel-plugin-tcomb/issues/24 (keep things DRY)
- `tcomb-json-schema`: should a `object` schema compile to a struct or a pojo?
  - choosing pojo would be a breaking change for `tcomb-form` (not acceptable at the moment)
- `tcomb-react`: AFAIK none

/cc @giogonzo

**Comment by ctrlplusb** [comment]
Firstly thanks @gcanti for firstly entertaining this idea, and secondly for producing such a thoughtful response!

My feedback...

__identity function approach__

i.e.
```
// tcomb types are glorified identity functions
const foo = Foo({ x: 1, y: 2 }); // => { x: 1, y: 2 } (not even touched)
``` 

Brilliant!  That is a far better idea than my initial proposal. 💖 

__Missing requirements__

_interface, pojo, or object_
After some consideration I personally feel that `interface` is the best candidate for the type name.  I initially warmed to `pojo`, but with further thinking I am not convinced that this name would communicate the intentions of the type.   More on this below. 

_own or prototype scoped_
I completely prefer including prototype properties for the type assertions. This goes a long way in allowing us to assert behaviour capabilities of a type, which your `serializable` example perfectly encapsulates.  And this I feel is a compelling reason to name it `interface`, as I feel `interface` is really clear at communicating behaviour intentions.

__Performance__

Yep, agree with you there.  Performance will certainly take a hit.

The babel plugin and #174 could alleviate this - i.e. disable type annotations for production.

__Consequences on other libraries__

  - `tcomb-validation`: 👍 
  - `tcomb-doc`: 👍 
  - `babel-plugin-tcomb`: 👍 👍 
  - `tcomb-json-schema`: Personally I believe that it json schema output should remain as a `struct` as a user is expecting an actual instance output.  Perhaps we need to think of this from another angle; validate that a JSON schema meets the requirements of an `interface`? A meta check of sorts.
  - `tcomb-react`: 👍

**Comment by gcanti** [comment]
+1 for `interface` though is a reserved word (I want IE8 compatibility as much as I can). `inter`, `shape`, `duck`?

> whilst also having type assertions disabled for production...

(just a clarification: type assertions are already disabled for production, i.e. `process.env.NODE_ENV === 'production'`. 174 just proposes to disentagle this existing behavior from `process.env.NODE_ENV === 'production'`)

**Comment by ctrlplusb** [comment]
Good man! Better than most, still considering IE8! :-)

My vote is for `inter`. 

Ta on the clarification of that. Good to know!

**Comment by gcanti** [comment]
You can track the progress here:

- [x] add "Struct" prefix to structs default name
  - [x] update tests
- [x] add interface combinator
  - [x] add tests
- [x] export `inter` and `interface` alias
- [ ] `extend` static function similar to Struct's `extend`
  - [ ] add tests
- [ ] struct's `extend` accepts also interfaces other than objects and structs
  - [ ] add tests

and here https://github.com/gcanti/tcomb/pull/196

**Comment by ctrlplusb** [comment]
What a turnaround time! Amazing thanks man.

Please let me know if I can help in any way.

This is a super exciting addition.

**Comment by ctrlplusb** [comment]
Made my day! Incredible work man.

**Comment by gcanti** [comment]
> Please let me know if I can help in any way

@ctrlplusb thanks, maybe a review / refactoring of the documentation? https://github.com/gcanti/tcomb/blob/master/docs/API.md#the-interface-combinator

**Comment by ctrlplusb** [comment]
@gcanti brilliant, thank you so much for all of this.  I've had a brief read of the docs and seems to all OK at this stage.  I'm going to pull this down and try and reference this in project and see how it holds up.

Sorry for the late reply on this, not a sign of disinterest - family all picked up an illness so been KO.

**Comment by ctrlplusb** [comment]
Oki, now that I am starting to use it, whilst reviewing the docs alongside I think the following part of the docs may be incorrect?

```
    const Point = t.struct({
      x: t.Number,
      y: t.Number
    }, 'Point');

    const Bar = t.interface({
      point: Point
    }, 'Bar');

    const bar = Bar({ point: { x: 0, y: 0} });
    Point.is(bar.point);
```

Should this not be, the following:

```
    const Point = t.interface({
      x: t.Number,
      y: t.Number
    }, 'Point');

    const Bar = t.struct({
      point: Point
    }, 'Bar');

    const bar = Bar({ point: { x: 0, y: 0} });
    Point.is(bar.point);
```

This seems more intuitive to the type for me.

Was it a typo or am I misunderstanding an alternative case here?

**Comment by gcanti** [comment]
No it's intentional. It's not that important but shows that `interface`, pretty much like all other combinators, is able to "deserialize" structs (i.e `bar.point instanceof Point` is `true`). We can strip it out if you think is confusing.

**Comment by ctrlplusb** [comment]
Nope, thats fair enough I think, but I think a more standard interface usage example prior to this one may avoid some initial confusion.

**Comment by ctrlplusb** [comment]
Super busy with deliverables this first half of week, will send a PR with some proposed changes to docs when I get a chance.

**Comment by gcanti** [comment]
> will send a PR with some proposed changes to docs when I get a chance

Great. Take your time and thanks again.
