### ISSUE TITLE
More intelligent immutability update handling.

### ISSUE THREAD

**Issue by ctrlplusb** [gcanti/tcomb#199]
Using tcomb types and their immutability helpers I get the following result:
```
const Person = t.struct({ name: t.String,  surname: t.String });
const bob = Person({ name: `Bob`, surname: `Builder` });
const stillBob = Person.update(bob, { $merge: { name: `Bob`, surname: `Builder` } });
console.log(bob === stillBob); // false
```

"bob" is no longer considered "bob" even though I technically didn't update any of his values. It would be great if the immutability helpers would have higher intelligence in this regard; i.e. reference check the props and simply spit out the original object if none have changed.  

If so this greatly simplifies my workflow as I don't need to do manually checking pre updates in order to avoid any state update propagation through my React app.  One example benefit, I am sure there are many more.

I have used a previous immutability helper library by the name of `timm` which does have the behaviour I am requesting, an example:
```
const mary = { name: `Mary`, surname: `Fairy` };
const stillMary = timm.merge(mary, { name: `Mary`, surname: `Fairy` });
console.log(mary === stillMary); // true
```

http://guigrpa.github.io/timm/

**Comment by ctrlplusb** [comment]
FYI, I tried the following, which actually works:
```
const Person = t.struct({ name: t.String,  surname: t.String });
const bob = Person({ name: `Bob`, surname: `Builder` });
const anotherBob = timm.merge(bob, { name: `Bob`, surname: `Builder` });
console.log(bob === anotherBob); // true
```

Useful alternative for those in the need.

**Comment by ctrlplusb** [comment]
> __Adding other commands__
> You can add your custom commands updating the t.update.commands hash.

I shall try this and post anything useful. :)

**Comment by ctrlplusb** [comment]
Ouch, not going to have much luck with providing a custom update command it seems:
```
const fred = Person({ name: `Fred`, surname: `Flintstone` });
const stillFred = Person.update(
  fred, { $noop:  { /* won't even be used */ } }
);
console.log(fred); // { name: `Fred`, surname: `Flintstone` }
console.log(stillFred); // { name: `Fred`, surname: `Flintstone` }
console.log(fred === stillFred); // false
```

I checked `update.js` and the following is called with the instance pre patch:
```
function getShallowCopy(x) {
  if (isArray(x)) {
    return x.concat();
  }
  if (x instanceof Date || x instanceof RegExp) {
    return x;
  }
  if (isObject(x)) {
    return mixin({}, x);
  }
  return x;
}
```

So a new object is always created. :cry:

**Comment by ctrlplusb** [comment]
Current workaround:
```
const fred = Person({ name: `Fred`, surname: `Flintstone` });
const stillFred = Person(timm.merge(fred, { name: `Fred`, surname: `Flintstone` });
console.log(fred); // { name: `Fred`, surname: `Flintstone` }
console.log(stillFred); // { name: `Fred`, surname: `Flintstone` }
console.log(fred === stillFred); // true
```

**Comment by gcanti** [comment]
Definitely it's a flaw in the `update` design, thanks for pointing out and for the link to `timm`. I'll dig into this asap.

**Comment by gcanti** [comment]
@ctrlplusb got a fix https://github.com/gcanti/tcomb/pull/200

**Comment by ctrlplusb** [comment]
You are a God!  Wow man, epic turnaround time as always.  Thank you for this.  I'll update my project to point to the github instance and will give it a run through over the next few days.  Writing tons of code and unit tests asserting all these things so should be a good test for it.

Thanks. :)
