### ISSUE TITLE
strictness (structs and interfaces)

### ISSUE THREAD

**Issue by gcanti** [gcanti/tcomb#203]
**Description**

Currently `struct`s and `interface`s are loose (you can pass additional props):

```js
import t from 'tcomb'

const Person = t.struct({
  name: t.String,
  surname: t.String
}, 'Person')

Person({name: 'Giulio', surname: 'Canti'})
Person({name: 'Giulio', surname: 'Canti', age: 42}) // => OK

const PersonI = t.interface({
  name: t.String,
  surname: t.String
}, 'PersonI')

PersonI({name: 'Giulio', surname: 'Canti'})
PersonI({name: 'Giulio', surname: 'Canti', age: 42}) // => OK
```

I'm thinking about a `strict` boolean flag which will check for additional props:

```js
// should throw `[tcomb] Invalid additional prop "age" supplied to Person`
Person({name: 'Giulio', surname: 'Canti', age: 42})
```

**Benefits**

- avoid typos: `Person({nam: 'Giulio', surname: 'Canti'})` (`nam` instead of `name`). Especially useful for optional props
- more control over the value passed in

**Requirements**

- should be backward compatibile
- should go in the `meta` object

**Consequences on other libraries**

- tcomb-doc: should output the new flag
- tcomb-validation: should check for additional props

**How to set the new flag?**

Not sure. There are at least 2 options:

1) manually set `Person.meta.strict = true`

```js
const Person = t.struct({
  name: t.String,
  surname: t.String
}, 'Person')

Person.meta.strict = true
```

2) (my preference) change `struct` signature from `(props, [name])` to `(props, [name | options])` where `options = { name: maybe(String), strict: maybe(Boolean) }`. Same for `interface`s.

```js
const Person = t.struct({
  name: t.String,
  surname: t.String
}, { name: 'Person', strict: true })
```

3) other?

/cc @giogonzo

**Comment by gcanti** [comment]
Related PR https://github.com/gcanti/tcomb/pull/204

**Comment by ctrlplusb** [comment]
My vote is for Option 2. :)

**Comment by minedeljkovic** [comment]
I think it would be useful to be able to set this option globally too.

**Comment by gcanti** [comment]
@minedeljkovic Yeah, thanks for the suggestion. I'll add a  global default (locally overridable):

```js
t.struct.strict = false
t.interface.strict = false
```

**Comment by gcanti** [comment]
Closing as per https://github.com/gcanti/tcomb/commit/7ceb82e66088e74a96c11882e44dea0ed2300d61

**Comment by ctrlplusb** [comment]
This is so good.  I've updated my code to use the latest from github and I've already found a handful of bugs by switching the global strict flag. 👍 👍 🙇

**Comment by gcanti** [comment]
Good to hear, thank you for the feedback @ctrlplusb
