### ISSUE TITLE
RFC: Relax `isObject` contraint in interface combinator

### ISSUE THREAD

**Issue by gcanti** [gcanti/tcomb#214]
```js
import t from 'tcomb'

const ToStringable = t.interface({
  toString: t.Function
})

console.log(ToStringable.is(1)) // => false, should be true
```

- https://github.com/gcanti/tcomb/blob/master/lib/interface.js#L55
- https://github.com/gcanti/tcomb/blob/master/lib/interface.js#L97

/cc @ctrlplusb @giogonzo

**Comment by giogonzo** [comment]
as already discussed offline, removing the `isObject` checks looks 👍 to me
