### ISSUE TITLE
babel plugin for writing Flow compatible type annotations

### ISSUE THREAD

**Issue by gcanti** [gcanti/tcomb#216]
[babel-plugin-tcomb](https://github.com/gcanti/babel-plugin-tcomb)

Example 1. Type-checking functions

```js
function sum(a: number, b: number): number {
  return a + b;
}
```

Example 2. Defining domain models

```js
type Person = {
  name: string,
  surname?: string,
  age: number,
  tags: Array<string>
};

**Comment by rattrayalex** [comment]
Is this issue complete? `babel-plugin-tcomb` is published on npm

**Comment by gcanti** [comment]
Yes, it's complete, thanks
