### ISSUE TITLE
t.maybe creates keys for undefined values

### ISSUE THREAD

**Issue by jedmao** [gcanti/tcomb#217]
### Version

3.2.2

### Expected behaviour

```js
const Foo = t.struct({ bar: t.maybe(t.String) });
new Foo({}); // Struct{}
```

### Actual behaviour

```js
new Foo({}); // Struct { bar: undefined }
```

### Issue

The resolution of #183 makes it very difficult for me to upgrade our application to tcomb@3.x, because our tests have expected data written in JSON files and you cannot define `undefined` in JSON.

```js
JSON.stringify({ bar: undefined }); // "{}"
```

None of this would be a problem if the following Jasmine test would pass:

```js
expect({ bar: undefined }).toEqual({});
// Expected Object({ bar: undefined }) to equal Object({  })
```

### Possible Solutions

I can see two possible solutions to this problem:
  1. Just don't create the key-value pair for `undefined` values in a `t.maybe` scenario.
  1. Allow us to define a default value (like `null` or `""`) for a `t.maybe` scenario.

Unfortunately, I don't see a way to fix this w/o introducing another breaking change. Do you have a better suggestion?

**Comment by gcanti** [comment]
> Allow us to define a default value (like null or "") for a t.maybe scenario

Actually you can, from v3.2.0 (https://github.com/gcanti/tcomb/releases/tag/v3.2.0)

```js
import t from 'tcomb'

const Foo = t.struct({ bar: t.maybe(t.String) }, { defaultProps: { bar: null } })

console.log(new Foo({})) // => Struct {bar: null}
```

**Comment by jedmao** [comment]
Ahh, OK. Thanks.
