### ISSUE TITLE
serialization transformers

### ISSUE THREAD

**Issue by itajaja** [gcanti/tcomb#229]
Hello! Extending the approach to serialization described in [this post](https://gcanti.github.io/2014/09/12/json-deserialization-into-an-object-model.html), I'd like to perform a more advanced serialization/validation. Assume for example this input:

```js
{
    a: " my String ",
    b: "  "
}
```

I want to:
1) trim out the spaces from `a` and `b`
2) validate that both `a` and `b` are not empty strings when trimmed. (so that the input above would be invalid)

to achieve 2) alone I could use a refinement like `refinement(String, s => s.trim().length > 0)`, but to achieve 1) I'd have to add some sort of transformation step before (or after?) validation. I could write my own `transform = i =>  ({ a: i.a.trim(), b: i.b.trim() })` function but that doesn't scale well with bigger schemas, and it's hardly reusable. Ideally I'd like a way to leverage the tcomb type system to compose a transformer. Do you have any suggestions to achieve that?

Thanks!

**Comment by gcanti** [comment]
Maybe something along the lines of the `fromJSON` module:

```js
import t from 'tcomb' // v3.2.7
import fromJSON from 'tcomb/lib/fromJSON'

const json = {
  a: " my String ",
  b: "  "
}

const NonEmptyString = t.refinement(t.String, s => s.length > 0, 'NonEmptyString')

const Type = t.struct({
  a: NonEmptyString,
  b: NonEmptyString
})

NonEmptyString.fromJSON = s => s.trim()

console.log(fromJSON(json, Type)) // throws [tcomb] Invalid value "" supplied to NonEmptyString
```

**Comment by itajaja** [comment]
TIL :)
keep up the awesome work!
