### ISSUE TITLE
Support for map combinator

### ISSUE THREAD

**Issue by singggum3b** [gcanti/tcomb#236]
Can we have support for map combinator ? also in babel-tcomb-plugin `Map<K,V>` ?

**Comment by gcanti** [comment]
If you want to represent and type check a mapping from a type `D` to a type `C` there is the `dict(D, C)` combinator.

In terms of babel-plugin-tcomb would be

```js
{[key: D]: C}
```

**Comment by singggum3b** [comment]
I'm refer to ES2016 Map type.
What i'm trying to do is having fromJSON convert and object to `Map<K,V>` type .
To do that i think i need a map combinator like `mapComb(k,v,name) {}`. I'm i wrong? is there any better way?

**Comment by singggum3b** [comment]
Map & Set in ES6
[http://www.2ality.com/2015/01/es6-maps-sets.html](url)

**Comment by gcanti** [comment]
Using a custom `fromJSON` [reviver](https://github.com/gcanti/tcomb/blob/master/docs/API.md#the-libfromjson-module)?

```js
import t from 'tcomb'
import fromJSON from 'tcomb/lib/fromJSON'

const MyType = t.interface({
  a: t.String,
  b: Map
})

const json = {
  a: 'a string',
  b: {
    x: 1,
    y: 2
  }
}

Map.fromJSON = value => {
  const map = new Map()
  for (var k in value) {
    map.set(k, value[k])
  }
  return map
}

fromJSON(json, MyType)
```

**Comment by singggum3b** [comment]
But that doesn't handle the case for example `Map<string,MyType>` where the result map should also have that type.

**Comment by gcanti** [comment]
You can apply `fromJSON` recursively

```js
// type alias
const MyMap = t.refinement(Map, () => true, 'MyMap')

const MyType = t.interface({
  a: t.String,
  b: MyMap
})

MyMap.fromJSON = value => {
  const map = new Map()
  for (var k in value) {
    map.set(k, fromJSON(value[k], MyType))
  }
  return map
}
```

Now, for what concerns a `map` combinator, its signature could be

```js
map(key: Type, value: Type, name) => Type
```

and I guess it could be implemented via `refinement`

```js
function map(key, value, name) {
  const MapKV = t.refinement(Map, function (x) {
    const entries = x.entries()
    let e
    while (!(e = entries.next()).done) {
      if (!key.is(e.value[0]) || !value.is(e.value[1])) {
        return false
      }
    }
    return true
  }, name)

  // MapKV.meta.kind = 'map' ?
  MapKV.meta.key = key
  MapKV.meta.value = value

  return MapKV
}
```

**Comment by singggum3b** [comment]
Yes, map combinator is what i needed.
I think map combinator is kind of basic type ( list & map is essential).
So do you intend to add support Map combinator or should i having it implemented externally ?
Also should tcomb support for easier implement of custom type combinator ? something like t.combinator() ?

**Comment by gcanti** [comment]
> should tcomb support for easier implement of custom type combinator ? something like t.combinator() ?

Usually all combinators contain very specific code, it's difficult to imagine such a general utility. What would it look like?

> So do you intend to add support Map combinator or should i having it implemented externally ?

Types that represents classes (i.e. roughly when you use `instanceof` in their `is` function) don't align well with the spirit of tcomb:

- sometimes are not inspectable at runtime (e.g. `Promise`)
- often are mutable and can't be frozen (`Date`, `Map`, `Set`)

the current policy is just to provide a basic support (`instanceof` checks) for them. I don't plan to add support in the core to `Map`, `Set`, `WeakMap`, `Buffer`, typed arrays, etc

For the moment I prefer to see combinators like the `map` above implemented in userland

**Comment by timoxley** [comment]
> the current policy is just to provide a basic support (instanceof checks) for them. I don't plan to add support in the core to Map, Set, WeakMap, Buffer, typed arrays, etc

@gcanti Are you suggesting something like `t.refinement(t.Object, o => o instanceof Map)`?

**Comment by timoxley** [comment]
Ahh  `const PromiseType = t.irreducible('PromiseType', (x) => x instanceof Promise);`
