### ISSUE TITLE
default values for interfaces?

### ISSUE THREAD

**Issue by timoxley** [gcanti/tcomb#238]
Structs filter out additional keys that aren't defined in the struct.
Interfaces do not filter additional keys but they can't define default values.

Currently there appears to be no way to have both default values and additional keys.

**Comment by gcanti** [comment]
Hi @timoxley,

while `struct`s build something (i.e. proper instances) `interface`s are pure structural types, i.e. they simply describes how an object should be made of. I don't think it's up to them to handle default values.

**Comment by timoxley** [comment]
Perhaps a way to disable key filtering for structs then?
