### ISSUE TITLE
t.Number doesn't support Infinity

### ISSUE THREAD

**Issue by dandelany** [gcanti/tcomb#239]
### Version

`tcomb` 3.2.9

### Expected behaviour

I would like to use `Infinity` as a value in a struct which expects a `t.Number`

### Actual behaviour

`Uncaught TypeError: [tcomb] Invalid value null supplied to Struct{a: Number}/a: Number`

### Steps to reproduce

1. `var X = t.struct({a: t.Number});`
2. `var foo = new X({a: 1})` - works fine
3. `var bar = new X({a: Infinity})` - throws `TypeError`

### Stack trace and console log

```
app.b3f9443.js:58533 Uncaught TypeError: [tcomb] Invalid value null supplied to Struct{a: Number}/a: Number(…)
fail	@	app.b3f9443.js:58533
assert	@	app.b3f9443.js:58503
Number	@	app.b3f9443.js:58596
create	@	app.b3f9443.js:58893
Struct{a: Number}	@	app.b3f9443.js:59453
(anonymous function)	@	VM1887:1
```

**Comment by gcanti** [comment]
Yeah, it's by design. You can easily define your own `SuperNumber ` type though

```js
import t from 'tcomb'

const Inf = t.irreducible('Infinity', x => !isFinite(x))
const SuperNumber = t.union([t.Number, Inf], 'SuperNumber')

SuperNumber(2) // ok
SuperNumber(Infinity) // ok
SuperNumber(-Infinity) // ok
```

**Comment by dandelany** [comment]
Gotcha - IMHO this seems like a slightly odd decision given that `typeof Infinity === 'number'`. But thanks for the workaround, and thanks in general for the very useful library!

**Comment by gcanti** [comment]
Yeah, I know, it's a kind of arbitrary decision from my part. I, for one, consider an odd decision that `typeof Infinity === 'number'` :)

(speaking of which, beware that `typeof NaN === 'number'`)

Anyway, keep in mind that `t.Number` is not magical, is just a `t.irreducible`-defined type, exported by `tcomb` as a convenience, but nothing prevents you to discard it (or even redefine it) if doesn't fit your expectations
