### ISSUE TITLE
disable freeze per-datatype

### ISSUE THREAD

**Issue by timoxley** [gcanti/tcomb#240]
I'm trying to retrofit tcomb into an existing system that does not make use of immutable data. 

I'm not calling `new t.interface` anywhere directly. However, I am using a `refinement` on an `interface` to add additional validation. I'm using this type to define the output of a `t.func`. Setting any types for `t.func` forces a new `interface` instance to be created, which then freezes my data.

It's an irony perhaps that in trying to encourage use of immutable data, tcomb mutates my data in a way that creates problems.

I think users should be able to disable the freeze behaviour without needing to change `process.env.NODE_ENV`.

 e.g. via meta

```js
t.interface({
  name: t.String
}, {
  name: 'DatatypeNode',
  freeze: false
})
```

I'd also argue that perhaps freezing isn't appropriate for interfaces, since in your own words:

> interfaces are pure structural types, i.e. they simply describes how an object should be made of.

**Comment by timoxley** [comment]
Current workaround is to not use tcomb types directly with `t.func`, instead just wrap each `type.is` up as a refinement like so:

```js 
// before
t.func([Section, Graph], GraphNode)

// after (very verbose):
const IsSection = t.refinement(t.Object, Section.is)
const IsGraph = t.refinement(t.Object, Graph.is)
const IsGraphNode = t.refinement(t.Object, GraphNode.is)

t.func([IsSection, isGraph], isGraphNode)
```

**Comment by gcanti** [comment]
Seems a good solution (you are losing precise error messages though), you can avoid the verbosity by defining a func wrapper which does the heavy lifting

```js
const myfunc = ... automatically build the irreducibles and call t.func ...

myfunc([Section, Graph], GraphNode)
```

you may want to define irreducibles instead of refinements

```js
const IsSection = t.irreducible('IsSection', Section.is)
```

> I think users should be able to disable the freeze behaviour

That would be dangerous since tcomb assumes you make use of immutable data
