### ISSUE TITLE
match doesn't handle classes

### ISSUE THREAD

**Issue by gcanti** [gcanti/tcomb#248]
Test case

``` js
import t from 'tcomb'

class A {}

console.log(t.match(new A(),
  A, () => 'A',
  t.Any, () => 'any'
))
```

throws [tcomb] Invalid type in clause #1

**Comment by gcanti** [comment]
@volkanunsal I tried some alternative implementations but given the particular API of `match`:

- `type` a tcomb type
- `guard` an optional predicate `(x: any) => any`
- `block` a function `(x: any) => any` called when the match succeeded

I'm afraid there no reliable way do detect a class instead of a guard or a block (they are all functions).

**Comment by volkanunsal** [comment]
Thanks for looking into this. I guess we need to come up with out own guard function to get around it. Seems a little hacky, but still better than nothing.
