### ISSUE TITLE
How to make multi selects built with list to be required.

### ISSUE THREAD

**Issue by rahimlila** [gcanti/tcomb#253]
### Version
tcomb form 0.6.3
Tell us which version you are using

I expected multi select  drop downs byuild with a list to be a required field by default, just like all other fields are. But the multiselect behaves like an optional field.

 property = t.list(t.enums({M: 'Male',F: 'Female'}));
How do I make things built with a list to be required?
```

**Comment by gcanti** [comment]
Wrong repo.

https://github.com/gcanti/tcomb-form/issues?utf8=✓&q=list%20required

First result.
