### ISSUE TITLE
Opening Enums in playground => Error: invalid Array.prototype.sort argument

### ISSUE THREAD

**Issue by alexicum** [gcanti/tcomb#260]
May be it should be in [tcomb-json-schema](https://github.com/gcanti/tcomb-json-schema) issues?

### Version

not sure what version is used in [playground](https://gcanti.github.io/resources/json-schema-to-tcomb/playground/playground.html)

### Expected behaviour

rendering without error

### Actual behaviour

Open playground and select "3. Enums" showing:

> Error!
> invalid Array.prototype.sort argument

**Comment by gcanti** [comment]
Honestly I don't remember a playground for tcomb (maybe something fairly old?), could you please post a link?

**Comment by alexicum** [comment]
sorry, I updated issue: it's playground for https://github.com/gcanti/tcomb-json-schema

**Comment by alexicum** [comment]
Hm, the problem is in Firefox (46.0.1)
Works in Chrome.

**Comment by gcanti** [comment]
Ah yes, tcomb-json-schema. It's outdated and no more mantained https://github.com/gcanti/tcomb-json-schema/pull/16

Thanks for reporting though
