### ISSUE TITLE
Consider updating typescript definition?

### ISSUE THREAD

**Issue by goodmind** [gcanti/tcomb#261]
### Version

3.2.15
### Expected behaviour

Should support latest public interface
### Actual behaviour

Throws error
### Steps to reproduce
1. `t.struct({}, { strict: false })`
2. See error
### Stack trace and console log

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

```
error TS2345: Argument of type '{ strict: boolean; }' is not assignable to parameter of type 'string'.
```

**Comment by gcanti** [comment]
Thanks for reporting, would you like to send a PR?

**Comment by goodmind** [comment]
#262
