### ISSUE TITLE
How to change model field enums

### ISSUE THREAD

**Issue by Paul-Todd** [gcanti/tcomb#266]
I need to change the enum values of a field at runtime as they are part of a select list but I cannot see how to do it. Any suggestions?

I have a model with an enum:

````
const AppointmentModel = t.struct({
    clients: t.enums({}, 'Clients'),
}, "AppointmentModel");
````

During runtime (I am using react so I override the componentWillReceiveProps) I need to change the clients enum to contain a list of clients which may have been updated externally.

How do I do that?
I tried with AppointmentModel.update and got nowhere

````
AppointmentModel.meta.props.clients = t.enums(props.clients, "Clients"); 
````

works but does not look like the correct or safe way of doing this.

Here is the form example:

````
<Form
   ref="form"
   value={this.state.values}
   options={AppointmentOptions}
   type={AppointmentModel} />
````

**Comment by gcanti** [comment]
Here's some suggestions in the `tcomb-form` repo https://github.com/gcanti/tcomb-form/issues/131#issuecomment-101920752
