### ISSUE TITLE
tcomb.Object is mutable

### ISSUE THREAD

**Issue by jfgodoy** [gcanti/tcomb#269]
Instances of t.Object are mutable, is this an expected behavior?

test case:
```
'use strict';

const t = require('tcomb');

const Properties = t.Object

let props = Properties({
	id: 1
});


props.id = 'mutated id';

console.log(props)
// prints { id: 'mutated id' }
```

**Comment by gcanti** [comment]
> is this an expected behavior

Yes (`Object` is an irreducible, like `Array`, `Any`, etc..). `irreducible`s, unlike `interface`s and `struct`s, are not frozen

**Comment by jfgodoy** [comment]
ok, thanks!
