### ISSUE TITLE
Do not stop on TypeError

### ISSUE THREAD

**Issue by ArmorDarks** [gcanti/tcomb#273]
Hi!

Thanks for a great lib!

For now there seems to be no clean way to prevent `tcomb` from throwing on first encountered TypeError, but throw all errors in the end of the check.

We need this to run tests in Jest and validate some models. Currently `tcomb` reports about first invalidation in `struct` and ejects, but we'd like it to run complete check.

I've tried to do something stupid. like this:

``` js
    let errors = []

    t.fail = (message) => { return errors = [...errors, message] }

    Schema(data)

    throw new TypeError(errors)
```

But it throws

```
    TypeError: Cannot read property 'length' of undefined

      at List (node_modules\tcomb\lib\list.js:40:32)
      at create (node_modules\tcomb\lib\create.js:9:104)
      at new Struct (node_modules\tcomb\lib\struct.js:82:19)
      at Struct (node_modules\tcomb\lib\struct.js:71:14)
      at Object.<anonymous> (tests\modules\other.test.js:36:5)
      at process._tickCallback (internal\process\next_tick.js:103:7)
```

Besides, it still feels like a hackable way rather than a solution to the issue.

Am I missing something?

**Comment by gcanti** [comment]
> We need this to run tests in Jest and **validate** some models

maybe https://github.com/gcanti/tcomb-validation ? its `validate` API returns a list of errors

**Comment by ArmorDarks** [comment]
Ouch, right! I saw `tcom-validation`, but I assumed that it's more for assertions like `true`/`false`. Missed that it also can return list of errors.

That exactly what we need, thanks!
