### ISSUE TITLE
Mixed Types

### ISSUE THREAD

**Issue by Claud** [gcanti/tcomb#277]
### Version

3.2.20

### Expected behaviour

How i can do like this - `function | object` ?

I use created custom types but it not cool. Maybe have more true way?

```
tcomb.irreducible('ObjectOrFunction', (n) => {
    return _.isObject(n) || _.isFunction(n);
});
```

**Comment by gcanti** [comment]
https://github.com/gcanti/tcomb/blob/master/docs/API.md#the-union-combinator
