### ISSUE TITLE
Validation in production mode

### ISSUE THREAD

**Issue by timbset** [gcanti/tcomb#285]
Hello!

I use tcomb 3.2.20. I need to validate users' input in production mode but it does not work. How can I configurate it to continue validation?

Here is a simple example:

```js
import t from 'tcomb';

function sum(a: number, b: number): number {
    t.Number(a);
    t.Number(b);
    const result = a + b;
    t.Number(result);
    return result;
}

console.log(sum({}, 2));
```

In the example I duplicated each check twice in the hope that at least one will work.

**Comment by gcanti** [comment]
Asserts are stripped out in production, though you could use the `is` function (outputs a boolean) or the `tcomb-validation` library (if you want more details)

**Comment by timbset** [comment]
That's great, thank you. Does it work with flow-like types to throw errors with minimum of code (without conditions and explicit error throwing)

**Comment by mqklin** [comment]
@gcanti  How can I use it inside `production` build? No way? I need it because I need to test production build

**Comment by mqklin** [comment]
Do you believe typescript is a better choice for now?

**Comment by timbset** [comment]
@mqklin TypeScript can be a good solution but you will need to validate external data anyway. I started using GraphQL in my project and it solved all the problems with types.

**Comment by mqklin** [comment]
@timbset I thought about `ts-io` but it's so cumbersome
