### ISSUE TITLE
Declare assertion issue

### ISSUE THREAD

**Issue by Gopikrishna19** [gcanti/tcomb#291]
version: **3.2.1**

line in question: https://github.com/gcanti/tcomb/blob/5bbaf1a8a473aa918410ce484233e5ab69008b96/lib/declare.js#L34

So can someone please explain why this is throwing error, and how the assertion works? Why would it assert the name _to be null and not to have a prototype_? and then reassign the same here:

https://github.com/gcanti/tcomb/blob/5bbaf1a8a473aa918410ce484233e5ab69008b96/lib/declare.js#L47

My code:
```js
import Type1 from 'somewhere';

const Type2 = t.declare('Type2');

const Children = t.struct({
    children: t.maybe(t.list(Type2), 'Types')
}, 'TypeChildren');

Type2.define(Type1.extend(Children, 'NestedType'));  // failing `isNil(name)` 
                                                     // if `NestedType` is given

Type2.prototype.toggle = function () {
  // do something
};
```

I am getting error from the above mentioned line, because I have a name provided. Also the error doesn't exactly explain whats wrong! it is saying "define a fresh type" ..  I even tried a singleton module (before code reading) but getting the same error.

Please help.

**Update:** The assertion is failing if `Type1` has a function defined on prototype not `Type2`

```js
Type1.protoype.fn = function () {  }

// :

Type2.define(Type1.extend(Children));  // failing `length(spec.prototype) === 0`

**Comment by gcanti** [comment]
the type given to `define` is a throwaway type, unnamed means

```js
Type2.define(Type1.extend(Children));
```

**Comment by Gopikrishna19** [comment]
@gcanti Thanks for the reply, I can live with that .. but I can't define any functions in the prototype either .. is there a way to get around that? I tried defining it before the `define` call but I get `prototype of null` error.

**Comment by gcanti** [comment]
> I can't define any functions in the prototype

Can't repro

```js
const Type1 = t.struct({
  foo: t.String
});

const Type2 = t.declare('Type2');

const Children = t.struct({
    children: t.maybe(t.list(Type2))
}, 'TypeChildren');

Type2.define(Type1.extend(Children));

Type2.prototype.getFoo = function () {
  return this.foo
};

Type2.prototype.getChildrenLength = function () {
  return (this.children || []).length
};

const x = Type2({ foo: 'bar', children: [{ foo: 'baz' }] })

console.log(x.getFoo()) // => bar
console.log(x.getChildrenLength()) // => 1
```

**Comment by Gopikrishna19** [comment]
I believe I made a mistake when I said defining a function on `Type2` throws error. It is coming from the `Type1`. Just checked it myself. So if you have a function `Type1`'s prototype, this is throwing the error. I apologise for the confusion.

Also @gcanti is there a specific reason for these assertions? This helps in identifying bugs from the extended type. It would say ''NestedType", instead of "Struct{ .. .children: Types}".

**Comment by gcanti** [comment]
IIRC those assertions were added to try to prevent using non-throwaway types

**Comment by Gopikrishna19** [comment]
Like what I have right now? Seems like intentional limitation. Can you consider this a bug and allow removing it? At least the second assertion?

**Comment by gcanti** [comment]
> Like what I have right now?

No, you are actually providing a fresh type (`Type1.extend(Children)`) so what you are doing seems legit, however the assert fails which is an unnecessary limitation. I guess I'll remove the assert (any better solution)?

**Comment by Gopikrishna19** [comment]
Thanks! Removing that limitation will be helpful, unless this is needed for something else, in that case, the only solution I have right now is not to extend but duplicate the `Type1` struct to the extending location.

**Comment by gcanti** [comment]
Just released a patch
