### ISSUE TITLE
[Question] Default value isnt applied to null

### ISSUE THREAD

**Issue by lamroger** [gcanti/tcomb#303]
Why is it expected that a default value should not be applied if the given value is `null` but is applied when given value is `undefined`?

https://github.com/gcanti/tcomb/blob/8a99cc33497a35e0d0a540bd58bd9cd869217dc8/test/struct.js#L180

Is null considered a valid t.String and therefore the default name isn't applied?

Looking a little more into validation, this example seems to show that validation is skipped on `null`

```
const t = require('tcomb-validation');
const validate = t.validate;

function isNotNull(i) {
  console.log(i);
  console.log(i !== null);
  return i !== null;
};

const NonNullString = t.refinement(t.String, isNotNull, 'NonNullString');

var Car = t.struct({
  name: t.maybe(NonNullString)
},
{
  defaultProps: {
    name: 'Subaru'
  }
 });


console.log('Car with null name: ');
console.log(Car({name: null}));
console.log('Car with undefined name: ');
console.log(Car({name: undefined}));
```

Output:

```
Car with null name:
Struct { name: null }
Car with undefined name:
Subaru
true
Struct { name: 'Subaru' }
```

**Comment by lamroger** [comment]
It looks like when t.maybe(Object) check `null`, it returns null according to https://github.com/gcanti/tcomb/blob/8a99cc33497a35e0d0a540bd58bd9cd869217dc8/test/maybe.js#L58
Also for undefined.

**Comment by lamroger** [comment]
Hi @gcanti , don't mean to bother but could you provide guidance when you have the time?  Thank you!

**Comment by gcanti** [comment]
@lamroger sorry for the late answer

> Why is it expected that a default value should not be applied if the given value is null but is applied when given value is undefined?

That's how default arguments are handled in JavaScript

```js
function f(a = 'foo') {
  return a
}

console.log(f()) // foo
console.log(f(null)) // null
```

**Comment by lamroger** [comment]
Hey @gcanti, thanks for the explanation! 

Another question, if the default argument isn't applied to `null`, then shouldn't `null` be tested against the type in t.maybe?

**Comment by gcanti** [comment]
> then shouldn't null be tested against the type in t.maybe?

Not sure I'm following, could you please elaborate?

**Comment by gcanti** [comment]
btw the test you pointed is loose, should be (I'll fix that)

```diff
it('should hydrate the elements of the maybe', function () {
  var T = t.maybe(Point);
-  assert.deepEqual(T(null), null);
-  assert.deepEqual(T(undefined), null);
+  assert.strictEqual(T(null), null);
+  assert.strictEqual(T(undefined), undefined);
  assert.ok(Point.is(T({x: 0, y: 0})));
});
```
