### ISSUE TITLE
Wrong writting cursor position on multiline field (Android only).

### ISSUE THREAD

**Issue by laranicolas** [gcanti/tcomb#304]
### Version

"tcomb-form-native": "^0.6.11"

### Expected behaviour

I would expect writting cursor be on the top of TextInput (as happened on iOS).

![form2](https://user-images.githubusercontent.com/1824473/34720837-01e44f68-f51f-11e7-91f3-dc6ed0d8b4e6.png)

### Tell us what should happen

I have a form with a multiline field and I used below code to build it:

```
var options = {
  fields: {
    comment: {
      label: 'Describe the type of Lead (optional)',
      multiline: true,
      stylesheet: {
          ...Form.stylesheet,
          textbox: {
              ...Form.stylesheet.textbox,
              normal: {
                  ...Form.stylesheet.textbox.normal,
                  height: 150
              },
              error: {
                  ...Form.stylesheet.textbox.error,
                  height: 150
              }
          }
      }
    }
  }
}
```

Appearance shows as textarea but the writting cursor (only on ANDROID) appear on the middle.

**Comment by gcanti** [comment]
@laranicolas please open an issue in the `tcomb-form-native` repo https://github.com/gcanti/tcomb-form-native
