### ISSUE TITLE
[Question] How to use async code with refinament

### ISSUE THREAD

**Issue by rkmax** [gcanti/tcomb#306]
I've started use tcomb recently I think is a very nice library and start to include into all my new code

but I'm thinking how is the best way to use refinament with async code, something like

```js
async function checkUnique(number) {
    const exist = await findOnMyDb(number);
    return !exist;
}

const UniqueNumber = t.refinement(t.Number, checkUnique, 'UniqueNumber');
```

and use like

```js
const MyType = t.struc({
  hello: t.String,
  code: UniqueNumber
})
// ...
const entry = await MyType({hello: 'world', code: 12345})
```

of course it's possible this is not the intended use for tcomb, but I want to hear your opinion

**Comment by gcanti** [comment]
> it's possible this is not the intended use for tcomb

Indeed, all checks are synchronous
