### ISSUE TITLE
Boolean literal

### ISSUE THREAD

**Issue by Ashoat** [gcanti/tcomb#308]
I'm trying to type a boolean literal, ie. the literal value `true`. I want it to match only that precise value.

First thought was `t.enums.of([true])`, but that matches on the string `"true"` as well. I've got it working with `t.intersection([t.Boolean, t.enums.of([true])])`, but that seems a bit verbose. Wondering if there's a better way.

**Comment by gcanti** [comment]
https://github.com/gcanti/tcomb/blob/master/docs/API.md#the-irreducible-combinator

```js
const True = t.irreducible('true', x => x === true)
```

**Comment by ArmorDarks** [comment]
I just wonder, isn't `t.refinament` wouldn't fit the situation better, since basically `true` is subset of `t.Boolean`, and thus it's logical to refine `t.Boolean`?

**Comment by gcanti** [comment]
Yes that's another legit option, though I guess is doesn't add too much in this case
