### ISSUE TITLE
validation doesn't seems to work.

### ISSUE THREAD

**Issue by kra3** [gcanti/tcomb#320]
### Version

3.2.27

### Provided

```node
var t = require("tcomb")

const Person = t.struct({
  name: t.String,
  age: t.maybe(t.Number) // an optional number
}, {name:'Person', strict: true});
```

### Expected behaviour

```Person({ name: 'Giulio', age: 'a string' });``` should throw error as per the documentation.

### Actual behaviour

However it is not throwing any errors, but validating.

### Steps to reproduce

1. Try out the example above at https://npm.runkit.com/tcomb

### Code

 https://runkit.com/embed/odapii20gtre
![image](https://user-images.githubusercontent.com/48812/40364930-ba918266-5dd3-11e8-9255-b2172b6bedf3.png)

Am I missing something here ?

PS: also if I try to add a string to age using `update` api, that also passes.

**Comment by gcanti** [comment]
@kra3 looks like RunKit is running with `process.end.NODE_ENV = 'production'`
