### ISSUE TITLE
T.Struct broken with NODE_ENV="production"

### ISSUE THREAD

**Issue by beac0n** [gcanti/tcomb#322]
### Version

3.2.27

### Expected behaviour

> var T = require('tcomb');
> var TestStruct = T.struct({ test: T.String});
> var x = TestStruct({test: false})
> TestStruct.is(x);
false

### Actual behaviour

> var T = require('tcomb');
> var TestStruct = T.struct({ test: T.String});
> var x = TestStruct({test: false})
> TestStruct.is(x);
true

### Steps to reproduce

run the script above with NODE_ENV="production"

**Comment by gcanti** [comment]
@beac0n thanks for opening this issue, this is not a bug though. The following line throws in development

```js
var x = TestStruct({test: false})
```

so everything comes after is not reliable and can't be used as a repro.

**Comment by beac0n** [comment]
@gcanti thanks for the quick answer.

How should I use tcomb for this use case in production then? 
Can you provide an example on how to use it properly in a production environment?

Thanks :)

**Comment by gcanti** [comment]
@beac0n `tcomb` is a runtime type system and is supposed to be used in development and disabled in production. If you want checks in production (for example for validating input, payloads etc..) you may want `tcomb-validation` (also if you are using typescript, check out [io-ts](https://github.com/gcanti/io-ts) which is written specifically for ts).

**Comment by gcanti** [comment]
Sure, thanks
