### ISSUE TITLE
union example from readme broken... 

### ISSUE THREAD

**Issue by mindreframer** [gcanti/tcomb#53]
```
var Price = t.struct({ currency: t.Str, amount: t.Num });
var PriceUnion = t.union([t.Num, Price])

var price_value = {currency: 'EUR', amount: 100}
// works fine
Price(price_value)
// throws "Error: union([Num, struct]).dispatch() returns no type" 
PriceUnion(price_value)
```

I'm using tcomb 2.1 (the latest release from bower) ... 

Would love to have it fixed... thx for the great library! 
Roman

**Comment by a-s-o** [comment]
I just ran into the same issue as described in your dispatch example. Great to see this solved. This is a very well thought out lib. Thanks :ok_hand:
