### ISSUE TITLE
Use struct name in error message?

### ISSUE THREAD

**Issue by aearly** [gcanti/tcomb#67]
Take this example code:

```
var MyNamedStruct = t.struct({
  foo: t.Str,
}, "MyNamedStruct");

var struct = MyNamedStruct({});
```

This throws an error with the mesage:

```
"Invalid `undefined` supplied to `Str`"
```

SInce I named the struct, wouldn't it be nicer to include the name in the error message?  Such as: 

```
"Invalid `undefined` supplied to `Str` in MyNamedStruct"
```

I can submit a PR if this is desirable, or not better accomplished elsewhere.

**Comment by peterjoel** [comment]
I am experiencing the same problems with identifying where errors occur in complex, nested structs. I read your comment about "the **debugger kicking in**", but this doesn't happen for me. In Chrome, my debugger kicks in when I use the `debugger` keyword in my code, or when an exception occurs and I have "stop on caught exceptions" checked. With tcomb I just get a message in my console.

**Comment by gcanti** [comment]
> I read your comment about "the debugger kicking in", but this doesn't happen for me.

Yes, that was before this https://github.com/gcanti/tcomb/issues/90

Now you can "Pause on exceptions" or override the default failure behavior:

```js
t.fail = function () {
  debugger;
  throw new TypeError(message);
};
```

**Comment by peterjoel** [comment]
Thanks!
