### ISSUE TITLE
t.func should handle optional arguments?

### ISSUE THREAD

**Issue by gcanti** [gcanti/tcomb#84]
An example:

```js
var t = require('tcomb');

var addWithMessage = t.func([t.Num, t.Num, t.maybe(t.Str)], t.Num).of(
    function(num1, num2, optionalMessage) {
        if (optionalMessage) {
            console.log(optionalMessage);
        }
        return num1 + num2;
    }
);

console.log(addWithMessage(1, 2)); // => returns a function (since the auto curry is in place), should execute the function instead?
```

cc @beckyconning

**Comment by beckyconning** [comment]
No I think it shouldn't. I think of maybe as a type of the provided type and null rather than as an optional argument flag. There are lots of situations where you need a curried function with arguments that can handle null. Very interesting idea though!! : )

**Comment by beckyconning** [comment]
This would also break the type signature paradigm of

addWithMessage :: Num -> Num -> Maybe(Str)

Instead it would be quite complex like

addWithMessage :: Num -> (Num, Maybe(Str))

Or something

**Comment by beckyconning** [comment]
I mean

addWithMessage :: Num -> Num -> Maybe(Str) -> Num

And 

addWithMessage :: Num -> (Num, Maybe(Str)) -> Num

Sorry my laptop is dead so I'm typing on my phone lol!

**Comment by gcanti** [comment]
Good remarks, thanks.

I can add:

- I try to avoid variadic functions when possible
- I like regular behaviours: rule out exceptions when possible and keep the code clean (as it is now)
- the only benefit seems writing `addWithMessage(1, 2)` instead of `addWithMessage(1, 2, null)`, not a big deal (in a type checking context)

It's reasonable trying to handle optional args, but given the drawbacks maybe it doesn't worth it.

cc @gavacho (you had a use case, what do you thing?)

**Comment by beckyconning** [comment]
I think If it's really important (I don't think I'd use it personally) then there should be an extra array at the end saying that arguments are optional. E.g

// 
var f = T.func([T.Num, T.Num, T.Str], T.Str, [false, false, true])
    .of(function (x, y, z)

**Comment by beckyconning** [comment]
But it does complicate things.

**Comment by gavacho** [comment]
As a thought experiment, let's take a look at lodash.  Many of that library's functions have optional arguments (e.g. https://lodash.com/docs#map)

I wanted to use tcomb to express that kind of function signature (for the sake of using tcomb to type-check arguments at runtime and avoid having to write that code myself all the time).  Perhaps this is not something tcomb should be concerned with (e.g. what happens when the optional argument is the first param?)

Maybe authors should be doing something like:

```js
var map = function(collection, callback, thisArg) {
    // handle all the different ways arguments could be provided
    return mapCore(collection, callback, null);
}

var mapCore = func(Collection, Callback, maybe(Obj)).of(
    function(collection, callback, thisArg) {
        ...
    }
);
```

I'd definitely welcome a better pattern tho!

**Comment by fernandocanizo** [comment]
Sorry to revive a closed issue, but this is exactly what  I'm looking for and couldn't find another reference to this on the web.

So, using the example from the [Little guide](https://github.com/gcanti/tcomb/blob/master/docs/GUIDE.md):

```
const SumType = t.func([t.Number, t.Number], t.Number);
const sum = SumType.of((a, b) => a + b);
```

I need to make a function whit an optional second parameter. So, before getting here I've tried in the REPL:
```
> var SumType = t.func([t.Number, t.maybe(t.Number)], t.Number);
> var sum = SumType.of((a, b) => a + b);
> sum(1)
TypeError: [tcomb] Invalid value null supplied to Number
```
Then tried:
```
> var SumType = t.func([t.Number, t.maybe], t.Number);
> var sum = SumType.of((a, b) => a + b);
> sum(1)
TypeError: [tcomb] Invalid value [
  1
] supplied to arguments of function (Number, maybe) => Number (expected an array of length 2)
```

So I decide to avoid the `.func` combinator:
```
> var sum = (a, b) => { t.Number(a); t.maybe(t.Number(b)); return a + b; }
> sum(1)
TypeError: [tcomb] Invalid value undefined supplied to Number
// now it doesn't even work with the proper parameters :scream:
> sum(1,2)
TypeError: [tcomb] Invalid argument type 2 supplied to maybe(type, [name]) combinator (expected a type)
```

What would be the proper way to build a function with and optional parameter that gets checked by tcomb and throws either if input or output (that was the main reason to use the func combinator) are not the expected ones? (Considering I want to have optional parameters)

**Comment by fernandocanizo** [comment]
Sorry, I'm new to tcomb and I thought `t.maybe` combinator could be used directly. Now I see that I need to build a new type first, so I tried:

```
var OptionalNumber = t.maybe(t.Number, 'OptionalNumber')
var SumType = t.func([t.Number, OptionalNumber], t.Number)
var sum = SumType.of((a, b) => a + b)
sum(1)
TypeError: [tcomb] Invalid value null supplied to Number
```

I see that if for instance I define sum like:

```
var sum = SumType.of((a, b) => b ? a + b : a)
// Then I can perfectly `sum` a single paramenter:
sum(1) // 1
```
But now I'm checking for `b`, what's the point of using tcomb?

Well, I understand it covers other cases, but I think it should cover this one too.

What am I missing?

Extra questions:

Is like I'm assuming and one cannot use `t.maybe` combinator directly on a `t.func` definiton? Or is it that I've used it wrong in my examples? (I'm referring in particular to this now:
```
var SumType = t.func([t.Number, t.maybe(t.Number)], t.Number)
var sum = SumType.of((a, b) => a + b)
sum(1)
TypeError: [tcomb] Invalid value null supplied to Number
```

By directly I mean: without defining a new type first.

Another consideration: doesn't it get too verbose? Imagine we would need optional values for every type, then there's a lot of types to type.

I hope someone can shed some light on this.

**Comment by gcanti** [comment]
@fernandocanizo It's the codomain check that (correctly) fails

```js
sum(1) = 1 + undefined = NaN
```

`JSON.stringify(NaN) = 'null'` explains the weird error message "Invalid value null supplied to Number" (should be "Invalid value NaN supplied to Number")

**Comment by fernandocanizo** [comment]
Oh! Thanks, I was so puzzled about that error message. So it's ok to use directly `t.maybe(t.Number)` without defining a new type, great.

Now I tried:
```
var SumType = t.func([t.Number, t.maybe(t.Number)], t.Nil)
var sum = SumType.of((a, b) => a + b)
sum(1)
TypeError: [tcomb] Invalid value null supplied to Nil
```

Which got me puzzled again cause docs say:
> There are 2 additional built-in types: t.Nil: null or undefined

So I went for `t.Any`:
```
var SumType = t.func([t.Number, t.maybe(t.Number)], t.Any)
var sum = SumType.of((a, b) => a + b)
sum(1)
NaN
```

**Comment by fatso83** [comment]
@fernandocanizo I am no expert, but I think that you need to handle the logic of making the output correct yourself. `tcomb` can only validate that you have done so. Saying that, I would expect your function to have looked like this: 

```javascript
> var SumType = t.func([t.Number, t.maybe(t.Number)], t.Number)
undefined
> var sum = SumType.of((a, b) => a + (b||0))
undefined
> sum(1)
1
> sum(1,2)
3
```
```

**Comment by fernandocanizo** [comment]
Sounds logical. It's true I wasn't handling the case of second parameter not coming. Thanks :)
