### ISSUE TITLE
remove util namespace and publish v1.0.0

### ISSUE THREAD

**Issue by gcanti** [gcanti/tcomb#87]
@beckyconning tcomb's API is stable now, if you agree I'd publish version 1.0 (followed by v1.0 of tcomb-validation) in the next few days

**Comment by nelix** [comment]
Looking forward to this

**Comment by gcanti** [comment]
Hi Nathan, 
do you have suggestions before v1.0? or is everything ok?

**Comment by nelix** [comment]
I'm keen, although I am interested to see what I will do in place of getKind.

**Comment by gcanti** [comment]
well just access <type>.meta.kind (there is no problem to keep `getKind` though)

before

```js
// tcomb-validation snippet
function recurse(x, type, path) {
  var kind = t.util.getKind(type); // getKind seems useless
  return validators[kind](x, type, path);
}
```

after

```js
function recurse(x, type, path) {
  return validators[type.meta.kind](x, type, path);
}
```

**Comment by nelix** [comment]
I think after is better, it leaves room for people to make their own utilities and what not
