### ISSUE TITLE
Better error reporting?

### ISSUE THREAD

**Issue by fforw** [gcanti/tcomb#88]
I was wondering if there is an easy way to get more descriptive error messages.

Errors like "Error: Invalid argument `value` = `foo` supplied to irreducible type `Bool`" are not really optimal to locate the error with larger type definitions or maybe even recursive type definitions.

Can we get information about the current "path" within the object validation hierarchy?

**Comment by gcanti** [comment]
Hi, it was discussed here: #67

The gist is: when I designed tcomb my main goal was to leverage the debugger features (I have the debugger always active while developing). Error messages are just a fallback.

I have a plan for v2.0: merge tcomb, tcomb-validation and flowcheck libs. In particular flowcheck's design would provide better error messages since has the concept of "path".

**Comment by fforw** [comment]
For my purposes, this seems a little too focused on the developer and development mistakes. My original intention was more geared towards validation reporting and not development mistakes.

I was toying around with a JSON notation for creating tcomb type definitions and you can see how quickly the "turns on the debugger" feature starts to make no sense there, as I am mostly interested in reporting back problems to the UI, not dissimilar to what tcomb-form is doing.

How do you handle this in tcomb-form?

**Comment by gcanti** [comment]
> How do you handle this in tcomb-form?

For validations I use [tcomb-validation](https://github.com/gcanti/tcomb-validation) (based on tcomb)

**Comment by timoxley** [comment]
FWIW this tool produces some of the best error messages:
https://www.npmjs.com/package/api-check

**Comment by gcanti** [comment]
Nice error messages, thanks for the link. I will borrow some ideas for

> I have a plan for v2.0: merge tcomb, tcomb-validation and flowcheck libs. In particular flowcheck's design would provide better error messages since has the concept of "path".

**Comment by th0r** [comment]
@gcanti It would be great to allow throwing custom errors in `subtype` to allow use-cases like this one:
```

**Comment by fforw** [comment]
@th0r 's suggestion would help me some, but the rest mostly doesn't cover my needs.

This all seems to be focusing too much on "writing code" aspect of things and errors being coding mistakes. 

I've been working with a model based programming platform a lot lately and while the outcome of that specific one in the end is rather slow and cumbersome, I still like the idea of modeling applications.

So I'm toying around with ideas to make model based programming more practical, faster etc. One way is to define a standard for defining a domain model in the sense of domain driven design.

Technically, it's a JSON notation to define the entity types within the domain, their relations and, and here comes tcomb into play, a structured data-payload definition for these entities. That part is basically a JSON notation for defining tcomb types. 

You see how the debugger is less then helpful in this case. I need to correlate the errors to the original type definition in general, to be able to then handle or report about it in the appropriate way for the domain use case.

**Comment by gcanti** [comment]
> This all seems to be focusing too much on "writing code" aspect of things and errors being coding mistakes.

This is precisely the juice of tcomb: I wrote this library with the goal of defining domain models with a concise syntax and adding invariants (asserts) to those domain models. When an assert fails (a **type** error) it's definitely a bug in my code. In production I could strip out all the invariants (like flowcheck does).

Conversely when I have to validate IO (validations) i.e. I can't be sure if the payloads are correct, I use tcomb-validation which returns all the errors and their paths.

tcomb and tcomb-validation have different goals. Doing validations with tcomb means catching the errors thrown by the asserts, I think it's not the correct approach.

@fforw are you doing what I call asserts or what I call validations? Or something else?

@th0r the `subtype(type, predicate)` combinator accepts a predicate, it can't throw.

**Comment by fforw** [comment]
This is all a work in progress and also a project I can't spend too much time on currently.

I will need validation in any case, I'm not sure if it goes beyond what tcomb-form offers, if I can make my ideas work with tcomb-form. Asserts might be useful, too, on the long run.

**Comment by th0r** [comment]
@gcanti Ok, maybe `tcomb` issues is the wrong place for my proposal. What I want is to show user, filling registration form, different "incorrect password" messages for different situations but I couldn't find a way to do it with `tcomb-form`.

**Comment by gcanti** [comment]
@th0r Ah, ok... maybe this could helpful:

The `error` option can also be a function with the following signature:

```
(value: any) => ?(string | ReactElement)
```

where `value` is the current field value, so you can return the proper error message.

Related:

https://github.com/gcanti/tcomb-form/blob/master/GUIDE.md#error-message

https://github.com/gcanti/tcomb-form/issues/115

https://github.com/gcanti/tcomb-form/issues/105#issuecomment-93410259

**Comment by th0r** [comment]
@gcanti Yes, `error` function is better than nothing, but I have to repeat `password` subtype's predicate logic here to show different errors.

**Comment by fforw** [comment]
@thor Predicates don't need to be anonymous inline functions. You can just as well define them as global / module and call them from both places.

**Comment by th0r** [comment]
@fforw Error function won't completely repeat predicate function, but there will be a lot of common logic:
```js
// Predicate function:
function testPassword(password) {
    password = password.trim();
    return password.length >= 6 && password.length <= 100 && PASSWORD_REGEXP.test(password);
}

// Error function:
function validatePassword(password) {
    // In `tcomb-form` field value, passed into error handler, can be `null`, so in addition we have to check it 
    password = (password || '').trim();
    if (!password) return 'Enter password';
    if (password.length < 6) return 'Password length must be at least 6 characters';
    if (password.length > 100) return 'Password length can not exceed 100 characters';
    if (!PASSWORD_REGEXP.test(password)) return 'Password must contain only these characters: ...';
}
```
Not very DRY =)

**Comment by fforw** [comment]
Then DRY it up a little

```javascript
function validatePassword(password)
{
    password = (password || '').trim();
    if (!password) return 'Enter password';
    if (password.length < 6) return 'Password length must be at least 6 characters';
    if (password.length > 100) return 'Password length can not exceed 100 characters';
    if (!PASSWORD_REGEXP.test(password)) return 'Password must contain only these characters:
   return null;
}

function predicate(password)
{
    return validatePassword(password) !== null;
}
```
Maybe even working with the indirection of using error code constants which are then transformed into internationalized error messages.
