### ISSUE TITLE
please remove debugger statements from code

### ISSUE THREAD

**Issue by timoxley** [gcanti/tcomb#90]
Same reasoning as https://github.com/gcanti/flowcheck/issues/15

**tl;dr**

> Forcing a debugger in there prevents the application developer from being able to control their own debugging environment.

**Comment by davidmfreese** [comment]
I think debugger should be an opt-in.

**Comment by gcanti** [comment]
Hi, 
You can override the default behaviour re-defining the `fail` function:
http://gcanti.github.io/tcomb/guide/index.html#utils

p.s.
If you come up with better implementations, could you share them?
Enforcing type safety and debugging type errors is the main goal of tcomb, so I'm interested in different solutions!

**Comment by timoxley** [comment]
> You can override the default behaviour re-defining the fail function:

ok that's a decent workaround for now, but I'd still like to strongly advocate removing debugger statement as it's highly intrusive. Perhaps I just don't see the scenario where the debugger statement does anything different than what the debugger would do by default anyway, can you explain? Are you targeting IE perhaps?

> If you come up with better implementations, could you share them?

Absolutely!

**Comment by gcanti** [comment]
> I just don't see the scenario where the debugger statement does anything different than what the debugger would do by default anyway

I thought about it, you are absolutely right. I will remove the `debugger` statement asap.

**Comment by timoxley** [comment]
:+1: :+1: thank you
