### ISSUE TITLE
tcomb.is reads backwards

### ISSUE THREAD

**Issue by timoxley** [gcanti/tcomb#91]
`Thing.is(instance)` is the opposite of how you'd say it naturally, at least in English: "Thing is instance". 

Suggesting maybe adding an alias of 'is' as 'check' or something so that it reads LTR a bit more naturally:

```js
Radio.is('a');
// vs
Radio.check('a');
```
or maybe go nuts:

```js
t.value('a').is(Radio)
```

**Comment by gcanti** [comment]
Well, since types represent sets, a better name would be `contains`:

```js
Str.contains('a'); // does the set Str contain the element 'a'?
```

 `is` is way shorter though
