### ISSUE TITLE
Lazy Tuples

### ISSUE THREAD

**Issue by m0x72** [gcanti/tcomb#95]
Hey @gcanti :)

Tuples are perfect for describing the types of a list of values, but require that matches have exactly the same amount of values as the tuple has types (n-tupel requires an n-ary list).

That's a super useful constrain, but there may be cases where lists of shorter length should match a tupel. I.e. a list of length (n-1) should match a n-tupel.
This is exactly the case for the [`items`](http://json-schema.org/latest/json-schema-validation.html#anchor37) property of arrays in json-schema. (Working on extending your tcomb-json-schema project).

I made a sample extension to tuples that allows them to be (given `n` is the number of types in an `n-tupel`: 
 - __lazy__: lists of length `< n` may successfully match against `n-tupels` if all values of the list match against the tupel's type of corresponding index
 - __additionalType__: if an `additionalType` is specified, lists of length > n may successfully match against an n-tupel, if all items at index > n match the `additionalType`-type.
 - __additionalType__ may only be specified when __lazy__ is true. That is, non-lazy tuples may never match lists of unequal length. (lazy tuples may match shorter lists when __lazy__ and no __additionalType__ is given, and shorter or larger lists when __lazy__ and __additionalType__ is given).

I just extended the tupel constructor with those properties (`tupel(types, name, bool:lazy, type:additionalType)`), since the tupel still keeps all of it's other properties. 
It may be cleaner and clearer though to seperate both kinds of tupels into different constructors.

Diff of the lazyTuples: https://github.com/gcanti/tcomb/compare/0f77882882...m0x72:0f8b51ded0

Any ideas? :)

**Comment by gcanti** [comment]
Hi @m0x72,
I'd prefer to keep the semantic of `tuple` simple and identical to its math counterpart (very strict).
I think that the nice thing about tcomb is the idea of combinator, not the actual implementation. The combinators provided are just the most common ones and you can easily extend this library writing you own combinators with few lines of code and matching your specific use case.

**Comment by m0x72** [comment]
Hey @gcanti, 
thanks for your input, makes sense. 
I guess i can even achieve something similar with the subtype combinator on a list of "Any". Something like: 
```js
t.subtype(t.list(t.Any), function (x) {
    var addType = t.Num;
    var types = [t.Num, t.Str];
    return x.every(function(xn, c) {
      if (c < types.length) return types[c].is(xn);
      else return addType.is(xn);
    });
  }, 'lazyList');
```
But then again, i'm loosing the ability to infer the list's types from the type definition. :(

But given that the use case is indeed pretty rare, i'll just extend tcomb as necessary for myself :)
